"use client";
import { useState, type FormEvent } from "react";
import { useQueryClient } from "@tanstack/react-query";
import Link from "next/link";
import { apiWrite } from "../lib/api";
import { useAccount, type Account } from "../lib/account";
import { Dialog } from "./Dialog";
import { Button } from "../kit/Button";

export function AccountDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [mode, setMode] = useState<"login" | "register">("login"); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const cache = useQueryClient();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setPending(true); setError(""); try { const result = await apiWrite<Account>(`/api/account/${mode}/`, { username: form.get("username"), password: form.get("password"), ...(mode === "register" ? { email: form.get("email") || "" } : {}) }); cache.setQueryData(["account"], result); await cache.invalidateQueries({ queryKey: ["me"] }); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Nie udało się zalogować."); } finally { setPending(false); } }
  return <Dialog open={open} onClose={onClose} title={mode === "login" ? "Zaloguj się" : "Załóż konto"}><form onSubmit={submit} className="sc-account-form"><p className="sc-t-body sc-text-2">Zapisuj własne tematy i komentuj materiały. Tworzenie nitek przez użytkowników jest dostępne w Twoim koncie.</p><label>Nazwa użytkownika<input required name="username" autoComplete="username" minLength={mode === "register" ? 3 : undefined} maxLength={mode === "register" ? 30 : 150} pattern={mode === "register" ? "[A-Za-z0-9_]{3,30}" : undefined} />{mode === "register" ? <span className="sc-t-caption sc-text-2">3–30 znaków: litery bez polskich znaków, cyfry lub podkreślenie.</span> : null}</label>{mode === "register" ? <label>E-mail <span className="sc-text-2">(opcjonalnie)</span><input name="email" type="email" autoComplete="email" /></label> : null}<label>Hasło<input required name="password" type="password" autoComplete={mode === "login" ? "current-password" : "new-password"} minLength={mode === "register" ? 8 : undefined} /></label>{error ? <p role="alert" className="sc-account-form__error">{error}</p> : null}<Button type="submit" fullWidth variant="primary" size="md" loading={pending}>{mode === "login" ? "Zaloguj się" : "Utwórz konto"}</Button><Button type="button" fullWidth variant="quiet" size="md" disabled={pending} onClick={() => { setMode(mode === "login" ? "register" : "login"); setError(""); }}>{mode === "login" ? "Nie masz konta? Zarejestruj się" : "Masz już konto? Zaloguj się"}</Button></form></Dialog>;
}

export function AccountControl() {
  const account = useAccount(); const cache = useQueryClient(); const [open, setOpen] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState("");
  async function logout() { setPending(true); setError(""); try { await apiWrite("/api/account/logout/", {}); cache.removeQueries({ queryKey: ["account-topics"] }); cache.removeQueries({ queryKey: ["topic-feed"] }); await Promise.all([cache.invalidateQueries({ queryKey: ["account"] }), cache.invalidateQueries({ queryKey: ["me"] })]); } catch (reason) { setError(reason instanceof Error ? reason.message : "Nie udało się wylogować."); } finally { setPending(false); } }
  return <div className="sc-account-control">{account.data?.authenticated ? <><Link href="/profile" className="sc-account-control__name" title="Twój profil">{account.data.user?.username}</Link>{account.data.user?.can_edit_threads ? <Link href="/editor" className="sc-account-control__name">{account.data.user?.is_staff ? "Zespół" : "Warsztat"}</Link> : null}<Button type="button" variant="quiet" size="sm" loading={pending} onClick={logout}>Wyloguj</Button></> : <Button type="button" variant="quiet" size="sm" disabled={account.isPending} onClick={() => setOpen(true)}>Zaloguj się</Button>}{error ? <span role="alert" className="sc-t-caption">{error}</span> : null}<AccountDialog open={open} onClose={() => setOpen(false)} /></div>;
}
