"use client";
import { useState } from "react";
import type { ThreadDetail } from "../types";
import { measurePost } from "../lib/xText";
import { Button } from "../kit/Button";

export function ThreadExport({ thread }: { thread: ThreadDetail }) {
  const [posts, setPosts] = useState<string[]>([]); const [notice, setNotice] = useState("");
  const sponsored = thread.is_sponsored || thread.thread_type === "sponsored";
  const mandatoryPrefix = sponsored ? `[${thread.sponsorship_label || "Nitka sponsorowana"}] ` : "";
  const prepare = () => { const ordered = [...thread.items].sort((a, b) => a.position - b.position); const main = thread.editorial_slot ? ordered[0] : [...ordered].reverse().find((item) => item.article.published_date) ?? ordered[0]; const items = main ? [main, ...ordered.filter((item) => item.id !== main.id)] : []; setPosts(items.map((item, index) => `${index + 1}/${items.length} ${item.editorial_note || item.article.title}\n${item.article.url}${index === 0 ? "\n" + window.location.origin + "/thread/" + thread.slug : ""}`)); setNotice("Sprawdź teksty przed publikacją. Zmiany tutaj dotyczą wyłącznie eksportu."); };
  return <section className="sc-thread-export"><header><h2 className="sc-t-title-s">Eksport nitki</h2><p className="sc-t-body sc-text-2">Przygotuj materiały do własnego posta. Publikację zawsze zatwierdzasz na X.</p></header><Button type="button" variant="secondary" size="md" onClick={prepare}>Przygotuj do publikacji na X</Button>{notice ? <p role="status" className="sc-t-caption">{notice}</p> : null}{posts.map((post, index) => { const completePost = mandatoryPrefix + post; const stats = measurePost(completePost); return <section key={index} className="sc-thread-export__post">{sponsored ? <p className="sc-t-caption">Stałe oznaczenie eksportu: {mandatoryPrefix}</p> : null}<label className="sc-thread-export__label">Post {index + 1} · {stats.weightedLength}/280<textarea value={post} onChange={(event) => setPosts((current) => current.map((value, itemIndex) => itemIndex === index ? event.target.value : value))} rows={4} /></label>{sponsored ? <p className="sc-t-caption sc-text-2">Oznaczenie sponsorowania zostaje dodane przy kopiowaniu i jest uwzględnione w limicie.</p> : null}{!stats.valid ? <p role="alert" className="sc-t-caption">Skróć tekst lub usuń niedozwolone znaki przed skopiowaniem.</p> : null}<Button type="button" variant="secondary" size="sm" disabled={!stats.valid} onClick={async () => { try { await navigator.clipboard.writeText(completePost); setNotice(`Skopiowano post ${index + 1}.`); } catch { setNotice("Nie udało się skopiować. Użyj widocznego tekstu wraz z oznaczeniem sponsorowania."); } }}>Kopiuj post {index + 1}</Button></section>; })}</section>;
}
