import { InfoPage } from '@spin-clinic/ui/kit';

export const metadata = { title: 'Prywatność i cookies · spin.clinic' };

export default function PrivacyPage() {
  return <InfoPage eyebrow="INFORMACJE" title="Prywatność i cookies" lead="Kto przetwarza dane w spin.clinic, w jakim celu, komu je powierzamy i jak długo je przechowujemy.">
    <section><h2>Połączenie konta X</h2><p>Po wybraniu logowania lub połączenia z X pobieramy identyfikator konta i nick, aby rozpoznać Twoje konto. Możesz wybrać nick z X jako publiczną nazwę z odnośnikiem do profilu. Nie zapisujemy tokenów dostępu ani nie publikujemy w Twoim imieniu. Identyfikator i nick przechowujemy do rozłączenia X w ustawieniach lub usunięcia konta. X nie przekazuje nam adresu e-mail; do publikowania dodaj i potwierdź go osobno. Przy dodawaniu publicznego linku do wpisu możemy pobrać przez oEmbed autora, datę i krótki tekst. Karta nie wczytuje skryptów X w Twojej przeglądarce.</p></section>
    <section><h2>Administrator danych</h2><p>Administratorem danych osobowych w serwisie spin.clinic jest iapply sp. z o.o., pl. Wolności 16, 61-739 Poznań, KRS 0001133291, NIP 7831915094, REGON 529962488. W sprawach prywatności napisz na <a href="mailto:kontakt@spin.clinic">kontakt@spin.clinic</a>.</p></section>
    <section><h2>Dane konta</h2><p>Przy rejestracji podajesz nick, adres e-mail, hasło oraz oświadczenie o ukończeniu 18 lat. Hasło przechowujemy w postaci zabezpieczonego skrótu. Bio jest opcjonalne. Zapisujemy Twoje nitki, komentarze, oceny, głosy na wywiady, zgłoszenia, obserwowanych, zapisane treści i wyciszenia. Nick, bio i opublikowane nitki są publiczne. Listę komentarzy na profilu możesz włączyć w ustawieniach; komentarze pod nitkami pozostają publiczne.</p></section>
    <section><h2>Po co je przetwarzamy</h2><p>Dane konta służą do zalogowania, ochrony przed nadużyciami i działania funkcji wybranych przez użytkownika. Komentarze oraz zgłoszenia służą moderacji. Prywatne nitki nie są publiczne ani nie są przekazywane modelom AI jako materiał do analizy.</p></section>
    <section><h2>Materiały ze źródeł i zewnętrzne usługi</h2><p>Baza przechowuje metadane publicznych materiałów: źródło, datę, odnośnik, sposób pozyskania i opis niezbędny do pokazania kontekstu. X i YouTube są używane wyłącznie przez ich oficjalne interfejsy i w dozwolonym zakresie. W Klinice spinu publiczne wpisy polityków z X - treść, autor, data, link oraz zdjęcia dołączone do wpisu - trafiają do dostawców modeli AI: Groq i NVIDIA (wstępna selekcja i konsylium), Google (Gemini: konsylium, sprawdzanie faktów, opis zdjęć, transkrypcja wywiadu dnia z YouTube) oraz Anthropic (Claude: konsultacje przy spornych diagnozach i ocena wywiadu dnia). Przy niedostępnych wpisach sprawdzamy w publicznym archiwum Internet Archive, czy istnieje kopia. Funkcje osób publicznych w fundacjach, stowarzyszeniach i spółkach potwierdzamy w oficjalnym API KRS Ministerstwa Sprawiedliwości, które udostępnia dane osób wyłącznie w formie zamaskowanej - takich danych nie zapisujemy; zapisujemy tylko nazwę podmiotu, numer KRS, funkcję i daty wpisu. Do tych usług nie przekazujemy danych czytelników: kont, reakcji ani komentarzy.</p></section>
    <section><h2>Newsletter</h2><p>Newsletter jest dostępny bez konta, na podstawie Twojej zgody (art. 6 ust. 1 lit. a RODO), którą możesz wycofać w każdej chwili linkiem w każdej wiadomości. Zapisujemy adres e-mail, status zapisu, daty zapisu, potwierdzenia i rezygnacji, miejsce zapisu na stronie oraz wersję zgody. Wiadomości wysyłamy przez pocztę home.pl S.A. (Szczecin), która obsługuje skrzynki domeny spin.clinic. Po wypisaniu zachowujemy adres z oznaczeniem rezygnacji, aby nie wysłać kolejnej wiadomości; na prośbę usuniemy go całkowicie.</p></section>
    <section><h2>Media społecznościowe</h2><p>Wybrane diagnozy, cytaty z publicznych wypowiedzi polityków i informacje o ich autorach publikujemy także we wpisach, grafikach i filmach na profilach spin.clinic (X, Facebook, Instagram, Bluesky, YouTube). Pełne analizy i ich ograniczenia są dostępne w serwisie. Gdy autor usunie wpis, usuwamy nasze publikacje tam, gdzie pozwala na to dana platforma. Korzystanie z naszych profili, komentowanie i wysyłanie wiadomości podlega również zasadom operatorów tych platform.</p></section>
    <section><h2>Komu powierzamy dane i gdzie są przechowywane</h2><p>Serwer i baza danych działają w centrum danych OVHcloud w Kanadzie (Beauharnois). Kanada ma decyzję Komisji Europejskiej stwierdzającą odpowiedni stopień ochrony danych, więc przekazanie danych poza Europejski Obszar Gospodarczy odbywa się na tej podstawie. Pocztę e-mail (kontakt, zgłoszenia, newsletter) obsługuje home.pl S.A. Publiczne wpisy polityków i materiały do analizy trafiają do dostawców modeli AI wymienionych wyżej. Nie sprzedajemy danych i nie przekazujemy ich do celów marketingowych.</p></section>
    <section><h2>Jak długo przechowujemy dane</h2><ul>
      <li><strong>Newsletter:</strong> do wycofania zgody; po wypisaniu zostaje tylko adres z oznaczeniem rezygnacji, aby nie wysłać kolejnej wiadomości - na prośbę usuniemy go całkowicie.</li>
      <li><strong>Konto:</strong> przez czas jego istnienia. Usunięcie w ustawieniach następuje od razu po potwierdzeniu hasłem. Rejestr decyzji moderacji pozostaje bez przypisania do konta.</li>
      <li><strong>Korespondencja i zgłoszenia:</strong> do 3 lat od ostatniego kontaktu - na wypadek roszczeń lub ponownego zgłoszenia tej samej sprawy.</li>
      <li><strong>Kopie zapasowe bazy:</strong> tworzone codziennie i automatycznie usuwane po 14 dniach.</li>
      <li><strong>Dzienniki serwera:</strong> nie prowadzimy dzienników dostępu z adresami IP czytelników; logi techniczne aplikacji służą wyłącznie wykrywaniu błędów.</li>
    </ul></section>
    <section><h2>Cookies i bezpieczeństwo</h2><p>Nie używamy cookies reklamowych ani analitycznych i nie śledzimy czytelników. W pamięci przeglądarki (localStorage) zapisujemy tylko Twoje ustawienia: motyw jasny lub ciemny i Twoje paski na stronie głównej - zostają na Twoim urządzeniu i nie trafiają do nas; usuniesz je, czyszcząc dane strony. Po udostępnieniu kont dojdzie techniczne cookie sesji, niezbędne do logowania. Miniatury zdjęć i filmów wyświetlamy bezpośrednio z serwerów X i YouTube, więc Twoja przeglądarka łączy się z nimi przy ich wczytywaniu.</p></section>
    <section><h2>Twoje prawa i kontakt</h2><p>Możesz uzyskać dostęp do swoich danych, sprostować je, usunąć konto lub zgłosić sprzeciw - napisz na <a href="mailto:kontakt@spin.clinic">kontakt@spin.clinic</a>. Przysługuje Ci też skarga do Prezesa Urzędu Ochrony Danych Osobowych. Podstawą przetwarzania jest zgoda (newsletter), wykonanie usługi (konto) albo prawnie uzasadniony interes administratora (bezpieczeństwo serwisu, obsługa zgłoszeń i roszczeń).</p></section>
  </InfoPage>;
}
