/** British English copy for the shared static documents. Polish copy is the lookup key. */
export const english = {
  "spin.clinic pomaga czytać publiczne wypowiedzi ze świadomością tego, jak powstaje przekaz. Dr. Spin analizuje konkretne komunikaty polityków: wskazuje techniki perswazji, przytacza cytaty i zestawia twierdzenia ze źródłami. Rządzących i opozycję obejmują te same zasady. Każdą diagnozę rozkłada na spinkę: łańcuch boksów (wpis, dokument, dane, nagranie), połączonych spinkami z wyjaśnieniem, co z czego wynika. Czytelnicy oceniają boksy i połączenia, komentują i układają własne spinki. Wyniki AI pokazujemy wraz z ograniczeniami, aby każdy mógł je sprawdzić i wyrobić własne zdanie. Projekt działa w wersji beta.": "spin.clinic helps readers understand how public statements are constructed. Dr. Spin analyses specific messages from politicians: it identifies persuasion techniques, quotes the material and checks claims against sources. The same rules apply to the governing camp and the opposition. Each diagnosis is laid out as a spinka: a chain of boxes (a post, a document, data, a recording) joined by clips that explain what follows from what. Readers rate the boxes and the connections, comment and build their own spinki. We present AI findings with their limitations so that anyone can check them and form their own view. The project is in beta.",
  "Działa obecnie: spinki Dr. Spina i czytelników, diagnozy wpisów polityków, dwa wywiady dnia (wybór Dr. Spina i wybór czytelników), „Przekaz dnia” obu obozów, archiwum usuniętych wpisów, raporty, dane i wykresy, konta z powiadomieniami oraz publikacja wybranych diagnoz w mediach społecznościowych.": "Available now: spinki by Dr. Spin and by readers, diagnoses of politicians' posts, two interviews of the day (Dr. Spin's pick and the readers' pick), both camps' “Message of the day”, an archive of deleted posts, reports, data and charts, accounts with notifications, and selected diagnoses published on social media.",
  "Klinika z Konsylium AI, spinki z oceną boksów i połączeń, izba przyjęć dla spinek czytelników, przepięcia, komentarze, konta, głosowanie na drugi wywiad dnia.": "the Clinic with the AI Council, spinki with ratings of boxes and connections, an admission room for readers' spinki, re-pins, comments, accounts and the vote on the second interview of the day.",
  "aplikacje mobilne z alertami o nowych spinach, śledzenie zmian i usunięć w źródłach, raporty dla instytucji na tych samych warunkach dla wszystkich.": "mobile apps with alerts about new spin, tracking of changes and deletions in sources, and reports for institutions on the same terms for everyone.",
  "własna maszyna do analiz na otwartych modelach i asystent, który odpowiada na pytania na podstawie naszej bazy źródeł.": "our own analysis engine on open models and an assistant that answers questions from our source base.",
  "Projekt": "Project",
  "Operator": "Operator",
  "Finansowanie": "Funding",
  "Obserwuj nas": "Follow us",
  "Kontakt": "Contact",
  "Co działa i co planujemy": "What works now and what is planned",
  "O NAS": "ABOUT",
  "Czym jest spin": "What spin is",
  "Politycy mają spin doktorów. Ty masz spin.clinic.": "Politicians have spin doctors. You have spin.clinic.",
  "Spin": "Spin",
  "Spin doktor": "Spin doctor",
  "spin.clinic": "spin.clinic",
  "Fakty podane tak, by działały na czyjąś korzyść: dobór słów, pominięcia, emocje. Nie zawsze kłamstwo, zawsze kierunek.": "Facts framed to favour someone: word choice, omissions, emotions. Not always a lie, always a direction.",
  "Doradca, który układa przekaz polityka: co powiedzieć, jak to ująć i co przemilczeć. Są po obu stronach sceny.": "An adviser who shapes a politician's message: what to say, how to frame it, what to leave out. Both sides have them.",
  "Strażnik po Twojej stronie: Konsylium AI rozkłada przekaz na techniki i sprawdza twierdzenia. Jedna miara dla wszystkich.": "A watchdog on your side: the AI Council breaks a message into techniques and checks its claims. One standard for all.",
  "Ta sama miara dla wszystkich": "The same standard for everyone",
  "spin.clinic łączy analizę konkretnych wypowiedzi ze źródłami i kontekstem do samodzielnego sprawdzenia.": "spin.clinic combines analysis of specific statements with sources and context that readers can check for themselves.",
  "spin.clinic pomaga czytać publiczne wypowiedzi ze świadomością tego, jak powstaje przekaz. Dr. Spin analizuje konkretne komunikaty polityków: wskazuje techniki perswazji, przytacza cytaty i zestawia twierdzenia ze źródłami. Rządzących i opozycję obejmują te same zasady. Obok Kliniki porządkujemy odnośniki do wiadomości, dokumentów i nagrań, zawsze z nazwą źródła, datą i linkiem do oryginału. Wyniki AI pokazujemy wraz z ograniczeniami, aby czytelnik mógł je sprawdzić i wyrobić własne zdanie. Wybrane diagnozy publikujemy także jako wpisy, grafiki i krótkie filmy w mediach społecznościowych - zawsze z linkiem do pełnej analizy. Projekt działa w wersji beta i rozwija się etapami.": "spin.clinic helps readers understand how public statements are constructed. Dr. Spin analyses specific messages from politicians: it identifies persuasion techniques, quotes the material and checks claims against sources. The same rules apply to the governing camp and the opposition. Alongside the Clinic, we organise links to news, documents and recordings, always with the source name, date and a link to the original. We present AI findings with their limitations so that readers can check them and form their own views. We also publish selected diagnoses as posts, graphics and short videos on social media - always with a link to the full analysis. The project is in beta and is being developed in stages.",
  "Jak wykorzystujemy AI": "How we use AI",
  "Metodologia analiz": "Analysis methodology",
  "Informacje dla redakcji": "Information for the press",
  "Film o serwisie": "Film about the service",
  "Operatorem serwisu jest iapply sp. z o.o., pl. Wolności 16, 61-739 Poznań, KRS 0001133291, NIP 7831915094, REGON 529962488.": "The service is operated by iapply sp. z o.o., pl. Wolności 16, 61-739 Poznań, KRS 0001133291, NIP 7831915094, REGON 529962488.",
  "Finansowanie i niezależność": "Funding and independence",
  "Projekt finansuje operator, iapply sp. z o.o., przy wsparciu czytelników. Ponosimy koszty API X, płatnych etapów analiz AI, transkrypcji i utrzymania serwisu; część zadań działa w bezpłatnych limitach usług.": "The project is funded by its operator, iapply sp. z o.o., with support from readers. We pay for the X API, paid stages of AI analysis, transcription and running the service; some tasks operate within services' free usage limits.",
  "Nie przyjmujemy darowizn od partii, polityków ani ich fundacji. Dane i raporty sprzedajemy każdemu na tych samych warunkach. Żaden klient ani darczyńca nie ma wpływu na diagnozy, listę czytanych kont ani treści serwisu.": "We do not accept donations from political parties, politicians or their foundations. We sell data and reports to everyone on the same terms. No client or donor has any influence over diagnoses, the list of accounts we read or the content of the site.",
  "Koszty i wsparcie projektu": "Project costs and support",
  "Najsilniejsze diagnozy publikujemy automatycznie także poza stroną - zawsze z linkiem do pełnej analizy i źródeł, bez oznaczania polityków.": "We also automatically publish diagnoses with the highest spin strength outside the website - always with a link to the full analysis and sources, without tagging politicians.",
  "- projekt, współpraca, media, sprawy techniczne, prywatność i zgłoszenia dotyczące diagnoz.": "- project enquiries, collaboration, media, technical matters, privacy and reports concerning diagnoses.",
  "- źródła, zgody wydawców i zakres dostępu.": "- sources, publishers' permission and scope of access.",
  "Zgłaszając błąd, dołącz link do diagnozy i źródła.": "When reporting an error, include a link to the diagnosis and sources.",
  "Jak obsługujemy zgłoszenia": "How we handle reports",
  "Działa obecnie: diagnozy wypowiedzi polityków, analizy wywiadów, „Przekaz dnia” obu obozów, raporty tygodnia, dane i wykresy oraz publikacja wybranych diagnoz w mediach społecznościowych.": "Currently available: diagnoses of politicians' statements, interview analysis, the Message of the day from both camps, weekly reports, data and charts, and publication of selected diagnoses on social media.",
  "Faza I - działa w wersji beta:": "Phase I - available in beta:",
  "wiadomości, Klinika z Konsylium AI, wywiady, raporty, wykresy, filmy z diagnoz i pilotaż autoryzowanych spinek.": "news, the Clinic with the AI Council (Konsylium), interviews, reports, charts, videos based on diagnoses and a pilot of authorised context threads.",
  "Faza II - planowana:": "Phase II - planned:",
  "konta i spinki czytelników, dyskusje oraz śledzenie zmian źródeł.": "reader accounts and threads, discussions and tracking changes to sources.",
  "Faza III - planowana:": "Phase III - planned:",
  "własna maszyna do analiz na otwartych modelach, asystent oparty na bazie źródeł i aplikacje mobilne.": "our own machine for analysis using open models, an assistant based on the source database and mobile apps.",
  "Newsletter o rozwoju projektu": "Newsletter on the project's development",
  "W skrócie": "At a glance",
  "Selekcja wpisów": "Post selection",
  "Zakres analizy": "Scope of analysis",
  "Werdykty i siła": "Verdicts and strength",
  "Zgodność modeli": "Model agreement",
  "Statusy twierdzeń": "Claim statuses",
  "Rodziny technik": "Technique families",
  "Słowa nacechowane": "Loaded words",
  "Jak liczymy dane": "How we calculate the data",
  "Ograniczenia": "Limitations",
  "Błędy i wycofanie": "Errors and withdrawal",
  "Selekcja": "Selection",
  "Strażnik czyta nowe wpisy i wybiera te z tezą do sprawdzenia.": "The Gatekeeper reads new posts and selects those containing a claim to check.",
  "Konsylium": "AI Council",
  "Kilka modeli różnych firm osobno ocenia ten sam wpis.": "Several models from different companies assess the same post independently.",
  "Dowody": "Evidence",
  "Twierdzenia trafiają do wyszukiwarki; ocena faktu wymaga źródła.": "Claims are submitted to a search engine; assessing a factual claim requires a source.",
  "Publikacja": "Publication",
  "Diagnoza ukazuje się automatycznie. Człowiek może ją tylko wycofać.": "The diagnosis is published automatically. A human can only withdraw it.",
  "Wyraźne techniki perswazji lub manipulacyjne przedstawienie treści.": "Clear persuasion techniques or a manipulative presentation of the content.",
  "Częściowy spin": "Partial spin",
  "Takie elementy są, ale nie określają całego komunikatu.": "These elements are present, but do not define the whole message.",
  "Bez spinu": "No spin",
  "Brak istotnego spinu w badanym materiale. To nie certyfikat prawdy.": "No significant spin in the material examined. This is not a certificate of truth.",
  "Nie da się ocenić": "Unable to assess",
  "Dane nie pozwalają rozstrzygnąć oceny.": "The available data does not allow a conclusive assessment.",
  "Potwierdzone": "Supported",
  "źródła wspierają twierdzenie": "sources support the claim",
  "Sprzeczne ze źródłami": "Contradicted by sources",
  "źródła przeczą twierdzeniu": "sources contradict the claim",
  "Wprowadzające w błąd": "Misleading",
  "istotne pominięcie, zniekształcenie lub nieuprawniony wniosek": "a significant omission, distortion or unwarranted conclusion",
  "Niezweryfikowane": "Unverified",
  "brak źródła albo nie da się tego sprawdzić": "no source is available or the claim cannot be checked",
  "Dane i wnioskowanie": "Data and reasoning",
  "Liczba bez punktu odniesienia": "Number without a reference point",
  "Wybiórcze dane": "Selective data",
  "Pominięcie kontekstu": "Omission of context",
  "Przeinaczenie faktów": "Misrepresentation of facts",
  "Teza bez dowodu": "Unsupported claim",
  "Fałszywa przyczynowość": "False causality",
  "Nadmierne uogólnienie": "Overgeneralisation",
  "Fałszywa analogia i skojarzenie": "False analogy and association",
  "Fałszywa alternatywa": "False dilemma",
  "Odwołanie do autorytetu": "Appeal to authority",
  "Emocje i przedstawienie": "Emotion and presentation",
  "Apel do emocji": "Appeal to emotion",
  "Straszenie": "Fearmongering",
  "Przesada": "Exaggeration",
  "Etykietowanie": "Labelling",
  "My kontra oni": "Us versus them",
  "Sugestia i niedopowiedzenie": "Insinuation and implication",
  "Spór i odpowiedzialność": "Dispute and responsibility",
  "Atak na osobę": "Personal attack",
  "Przypisywanie intencji": "Attributing intentions",
  "Zniekształcenie cudzego stanowiska": "Misrepresenting another person's position",
  "Zmiana tematu": "Changing the subject",
  "Przypisywanie sobie zasług": "Claiming credit",
  "liczba diagnoz w grupie i okresie; średnia arytmetyczna wyników diagnoz": "number of diagnoses in the group and period; arithmetic mean of diagnosis scores",
  "Techniki i rodziny": "Techniques and families",
  "liczba diagnoz z daną kategorią (raz na diagnozę), nie suma technik": "number of diagnoses containing a category (once per diagnosis), not the total number of techniques",
  "Twierdzenia": "Claims",
  "odrębne twierdzenia po scaleniu powtórzeń; niezweryfikowane osobno": "distinct claims after merging duplicates; unverified claims counted separately",
  "średnia liczba różnych słów lub zwrotów na diagnozę": "average number of distinct words or phrases per diagnosis",
  "Jednomyślność": "Unanimity",
  "diagnozy z co najmniej 2 odpowiedziami, w których wszystkie głosy są zgodne": "diagnoses with at least 2 responses in which all votes agree",
  "Polubienia": "Likes",
  "tylko wpisy z dostępną liczbą; brak danych to nie zero": "only posts with an available count; missing data is not zero",
  "METODOLOGIA": "METHODOLOGY",
  "Jak analizujemy przekaz": "How we analyse messages",
  "Diagnoza dotyczy konkretnego komunikatu, nie osoby. Poniżej: skąd biorą się wpisy, jak powstaje wynik i jak liczymy dane Kliniki.": "A diagnosis concerns a specific message, not a person. Below: where posts come from, how the result is produced and how we calculate the Clinic's data.",
  "Czytamy wpisy z obserwowanych kont X polityków i partii z ostatnich 3 dni. Strażnik daje każdemu wstępny wynik - to nie jest siła spinu.": "We read posts from the past 3 days on the X accounts of politicians and parties we follow. The Gatekeeper assigns each an initial score - this is not spin strength (0-100).",
  "Progi wyniku selekcji": "Selection score thresholds",
  "pomijany": "skipped",
  "do decyzji": "pending decision",
  "kolejka": "queued",
  "To próba wybranych wypowiedzi, nie cała debata. Więcej diagnoz jednej strony nie znaczy, że ta strona częściej stosuje spin. Brak diagnozy nie oznacza „bez spinu”.": "This is a sample of selected statements, not the entire debate. More diagnoses of one side do not mean that side uses spin more often. No diagnosis does not mean 'no spin'.",
  "Badamy": "We examine",
  "tekst wpisu": "post text",
  "zdjęcia i grafiki: opis i tekst na obrazie": "photos and graphics: descriptions and text within images",
  "tytuły i opisy podlinkowanych stron": "titles and descriptions of linked pages",
  "Nie badamy we wpisach": "We do not examine in posts",
  "filmów dołączonych do wpisu": "videos attached to the post",
  "tego, czego model nie odczytał - opisujemy to w ograniczeniach diagnozy": "anything the model could not read - we describe this in the diagnosis's limitations",
  "Wywiady": "Interviews",
  "mają osobny proces: transkrypcja i osobne oceny gościa oraz prowadzącego.": "follow a separate process: transcription and separate assessments of the guest and interviewer.",
  "Werdykty i siła spinu": "Verdicts and spin strength (0-100)",
  "Siła spinu to nasilenie rozpoznanych zabiegów - nie procent fałszu ani winy. Wynik to mediana ocen modeli; dla „bez spinu” najwyżej 20.": "Spin strength (0-100) measures the intensity of the techniques identified - not a percentage of falsehood or guilt. The score is the median of the models' assessments; for 'no spin' it is capped at 20.",
  "Werdykt to środkowa ocena Konsylium; przy remisie wybieramy łagodniejszą. Głosy „nie da się ocenić” nie wchodzą do mediany. Nie dopisujemy fikcyjnych głosów tam, gdzie oceniał jeden model.": "The verdict is the Council's middle assessment; in a tie we choose the milder one. 'Unable to assess' votes are excluded from the median. We do not add fictional votes where only one model assessed the material.",
  "ten sam werdykt": "the same verdict",
  "Tyle modeli dało werdykt równy wynikowi diagnozy. „Nie da się ocenić” liczy się do mianownika, brak odpowiedzi - nie. Obok pokazujemy rozrzut ocen siły.": "This is how many models gave the same verdict as the diagnosis. 'Unable to assess' counts in the denominator; a missing response does not. We also show the spread of strength scores.",
  "Modele mogą popełnić ten sam błąd, więc zgoda nie jest dowodem. Docelowo: co najmniej 4 odpowiedzi z 3 firm i model polski; przy limitach usług - 3 odpowiedzi z opisem braków.": "Models can make the same mistake, so agreement is not evidence. The target is at least 4 responses from 3 companies, including a Polish model; when service limits apply: 3 responses with missing contributions described.",
  "Aktualny skład": "Current membership",
  "Status faktu wymaga źródła z wyszukiwania - bez niego twierdzenie zostaje niezweryfikowane. Podobne twierdzenia łączymy przed liczeniem. W zestawieniach grupa „opinie” obejmuje dziś także fakty, których nie udało się sprawdzić.": "A factual claim's status requires a source from search results - without one, the claim remains unverified. We merge similar claims before counting. In summaries, the 'opinions' group currently also includes facts that could not be verified.",
  "21 kategorii w trzech rodzinach oraz „Inne”. Technika trafia do diagnozy tylko z cytatem z materiału i gdy wskaże ją co najmniej 2 członków Konsylium (przy 1-2 rozstrzygniętych głosach wystarczy jedno wskazanie). Najwyżej 6 technik na diagnozę.": "21 categories in three families, plus 'Other'. A technique appears in a diagnosis only with a quotation from the material and when at least 2 Council members identify it (with 1-2 conclusive votes, one identification is sufficient). At most 6 techniques per diagnosis.",
  "strach i zagrożenie": "fear and threat",
  "gniew i oburzenie": "anger and outrage",
  "pogarda i wyśmiewanie": "contempt and ridicule",
  "duma i wspólnota": "pride and community",
  "współczucie i krzywda": "compassion and harm",
  "Najpierw bierzemy wskazania modeli (słowo musi być we wpisie), a gdy ich brak - polski słownik. Liczymy różne słowa i zwroty, nie wszystkie wystąpienia. Samo nacechowane słowo nie przesądza o spinie.": "We first use the models' findings (the word must appear in the post), falling back to a Polish dictionary if none are available. We count distinct words and phrases, not every occurrence. A loaded word alone does not establish spin.",
  "Wykresy obejmują opublikowane, nieukryte diagnozy. Porównania dotyczą 30 dni według daty diagnozy.": "Charts cover published diagnoses that have not been hidden. Comparisons cover 30 days, based on the diagnosis date.",
  "Miara": "Measure",
  "Podstawa": "Basis",
  "Poniżej": "Below",
  "10 obserwacji": "10 observations",
  "oznaczamy małą próbę. To sygnał ostrożności, nie test statystyczny.": "we flag a small sample. This is a caution, not a statistical test.",
  "AI może pomylić cytat, kontekst, ironię, ocenę faktu albo kategorię techniki.": "AI may misinterpret a quotation, context, irony, a factual claim or a technique category.",
  "Modele różnych firm mogą mieć wspólne dane treningowe i uprzedzenia.": "Models from different companies may share training data and biases.",
  "Wyszukiwanie nie obejmuje całej wiedzy; źródła bywają nieaktualne.": "Search does not cover all knowledge; sources may be out of date.",
  "Limity usług zmieniają skład Konsylium i zakres badań.": "Service limits affect Council membership and the scope of checks.",
  "Wnioski dotyczą tej próby komunikatów - nie oceniamy prawdomówności osób.": "Conclusions concern this sample of messages - we do not assess people's truthfulness.",
  "Widzisz błąd?": "Spotted an error?",
  "Wyślij link do diagnozy, opis i źródła na": "Send a link to the diagnosis, a description and sources to",
  ". Tą samą drogą autor wypowiedzi może przesłać odpowiedź.": ". The author of the statement can submit a response through the same channel.",
  "Operator może wycofać całą diagnozę - zapisujemy datę i powód. Treści, werdyktu ani siły nie poprawia się ręcznie. Każde wycofanie, ukrycie prawne i odpowiedź autora znajdziesz w": "The operator can withdraw an entire diagnosis - we record the date and reason. Its content, verdict and strength are not edited manually. Every withdrawal, legal removal and author response is listed in the",
  "publicznym rejestrze korekt i odpowiedzi": "public register of corrections and responses",
  "Wycofania, ukrycia prawne i odpowiedzi autorów:": "Withdrawals, legal removals and author responses:",
  "Rejestr korekt": "Register of corrections",
  "Karta Konsylium": "Council Charter",
  "Droga wpisu": "The path of a post",
  "Kto co robi": "Who does what",
  "Jak łączymy głosy": "How we combine votes",
  "Narzędzia": "Tools",
  "Granice analizy": "Limits of analysis",
  "Zasady i błędy": "Rules and errors",
  "Strażnik czyta nowe wpisy polityków i wybiera te, w których jest teza do sprawdzenia.": "The Gatekeeper reads new posts by politicians and selects those containing a claim to check.",
  "Niezależne głosy": "Independent votes",
  "Kilka modeli różnych firm ocenia wpis osobno. Żaden nie widzi odpowiedzi innych.": "Several models from different companies assess the post separately. None sees the others' responses.",
  "Łączenie": "Combining votes",
  "Stałe reguły łączą głosy w jeden werdykt, siłę spinu i listę technik.": "Fixed rules combine votes into one verdict, a spin strength score (0-100) and a list of techniques.",
  "Źródła i badania": "Sources and checks",
  "Twierdzenia trafiają do wyszukiwarki, a laboratorium dodaje badania pomocnicze. Źródło musi pochodzić z wyników.": "Claims are submitted to a search engine, and the Laboratory adds supporting checks. Sources must come from the search results.",
  "Uzasadnienie": "Explanation",
  "Przewodniczący pisze diagnozę z ustaleń, recenzent sprawdza zgodność, językoznawca poprawia polszczyznę.": "The Chair writes the diagnosis from the findings, the Reviewer checks consistency and the Linguist corrects the Polish.",
  "Diagnoza ukazuje się automatycznie, z głosami modeli i ograniczeniami. Nikt nie edytuje jej treści. Wybrane wyniki trafiają też jako skróty i filmy do mediów społecznościowych - zawsze z linkiem do pełnej analizy.": "The diagnosis is published automatically, with model votes and limitations. No one edits its content. Selected results also appear as summaries and videos on social media - always with a link to the full analysis.",
  "Członkowie Konsylium": "Council members",
  "Każdy osobno podaje werdykt, siłę 0-100, techniki z dosłownym cytatem i twierdzenia do sprawdzenia.": "Each independently provides a verdict, spin strength (0-100), techniques with verbatim quotations and claims to check.",
  "Sprawdzanie faktów": "Fact-checking",
  "Gemini z wyszukiwarką Google": "Gemini with Google Search",
  "Szuka źródeł do każdego twierdzenia. Bez źródła twierdzenie zostaje niezweryfikowane.": "Looks for sources for each claim. Without a source, the claim remains unverified.",
  "Konsultant": "Consultant",
  "Claude (Anthropic) · płatny": "Claude (Anthropic) · paid",
  "Mocniejsze sprawdzenie faktów, gdy modele są podzielone (zgoda poniżej 2/3) albo spin jest silny (70/100 i więcej).": "More thorough fact-checking when models are divided (agreement below 2/3) or spin is strong (70/100 or above).",
  "Laboratorium": "Laboratory",
  "Badania pomocnicze: wydźwięk, wcześniejsze fact-checki, dane GUS, obecność cytatu w źródle. Nie zmieniają werdyktu.": "Supporting checks: sentiment, earlier fact-checks, GUS data and whether a quotation appears in its source. These do not change the verdict.",
  "Przewodniczący": "Chair",
  "Gemini (w zapasie inne modele)": "Gemini (other models as fallbacks)",
  "Pisze uzasadnienie wyłącznie z ocen Konsylium i dowodów. Nie może zmienić werdyktu, siły ani dodać techniki.": "Writes the explanation solely from the Council's assessments and evidence. Cannot change the verdict or strength, or add a technique.",
  "Recenzent": "Reviewer",
  "Nemotron (w zapasie inne modele)": "Nemotron (other models as fallbacks)",
  "Sprawdza, czy tekst zgadza się z ocenami i Kartą. Przy uwagach przewodniczący raz poprawia diagnozę; brak recenzji nie wstrzymuje publikacji.": "Checks whether the text matches the assessments and Charter. If issues are raised, the Chair revises the diagnosis once; the absence of a review does not prevent publication.",
  "Językoznawca": "Linguist",
  "Bielik (w zapasie PLLuM, Qwen, Gemini)": "Bielik (PLLuM, Qwen and Gemini as fallbacks)",
  "Poprawia tylko polszczyznę. Gdy poprawka wyraźnie zmienia długość tekstu albo nie jest po polsku, zostaje wersja przewodniczącego.": "Corrects only the Polish. If a correction substantially changes the text's length or is not in Polish, the Chair's version is retained.",
  "obsługiwane": "supported",
  "planowane": "planned",
  "Konsylium, łączenie głosów, przewodniczący, recenzent, językoznawca": "Council, vote aggregation, Chair, Reviewer, Linguist",
  "rdzeń każdej diagnozy": "core of every diagnosis",
  "źródła do twierdzeń": "sources for claims",
  "Claude z wyszukiwaniem": "Claude with search",
  "konsultacja przy sporze i silnym spinie, gdy pozwala budżet": "consultation for disagreement and strong spin, when the budget allows",
  "Słownik słów nacechowanych i 21 kategorii technik": "Dictionary of loaded words and 21 technique categories",
  "wspólny język diagnoz": "a shared vocabulary for diagnoses",
  "wydźwięk i mowa nienawiści - sygnał pomocniczy": "sentiment and hate speech - a supporting signal",
  "wcześniejsze sprawdzenia innych redakcji": "earlier checks by other newsrooms",
  "bezrobocie i wynagrodzenia w Polsce": "unemployment and wages in Poland",
  "czy cytat naprawdę jest w źródle (do 3 na diagnozę)": "whether the quotation really appears in the source (up to 3 per diagnosis)",
  "publiczna kopia wpisu, w tle": "public copy of the post, created in the background",
  "Własny detektor technik (XLM-RoBERTa)": "Our own technique detector (XLM-RoBERTa)",
  "na własnej maszynie": "on our own machine",
  "Eurostat, NBP, rejestry prawa": "Eurostat, NBP, legal registers",
  "szersze sprawdzanie liczb i przepisów": "broader checking of figures and legislation",
  "KONSYLIUM AI": "AI COUNCIL (KONSYLIUM)",
  "Kilka modeli AI,": "Several AI models,",
  "jedna diagnoza": "one diagnosis",
  "Wybrane wpisy polityków osobno ocenia kilka modeli AI różnych firm. Porównujemy ich głosy, szukamy źródeł i przygotowujemy wspólną diagnozę - z jawnym składem i ograniczeniami. Modele mogą się mylić.": "Several AI models from different companies independently assess selected posts by politicians. We compare their votes, look for sources and prepare a joint diagnosis - with transparent membership and limitations. Models can make mistakes.",
  "Film: jak działa spin.clinic": "Film: how spin.clinic works (in Polish)",
  "Droga wpisu do diagnozy": "From post to diagnosis",
  "Konsylium działa jak rada lekarska: kilku niezależnych specjalistów, osobne badania i jeden opis wyniku. Poniżej domyślna obsada ról - gdy model nie odpowie, zastępuje go kolejny. Rzeczywistych wykonawców pokazujemy przy każdej diagnozie.": "The Council works like a medical council: several independent specialists, separate examinations and a single report of the result. Below are the default role assignments - if a model does not respond, another takes over. Each diagnosis identifies the models that actually performed the work.",
  "Przykład obliczenia, nie rzeczywista diagnoza": "Illustrative calculation, not a real diagnosis",
  "Wynik": "Result",
  "ten sam werdykt · rozrzut od 30 do 80": "the same verdict · range 30 to 80",
  "Przykład obliczenia, nie rzeczywista diagnoza.": "Illustrative calculation, not a real diagnosis.",
  "Werdykt i siła": "Verdict and strength",
  "to środkowe oceny (mediana). Jeden skrajny model nie przesądza wyniku; przy remisie wybieramy łagodniejszą ocenę.": "are the middle assessments (median). One outlying model does not determine the result; in a tie we choose the milder assessment.",
  "Technika": "A technique",
  "wymaga dosłownego cytatu z badanego materiału. Przy co najmniej trzech rozstrzygniętych głosach muszą ją wskazać minimum dwa modele; przy jednym lub dwóch takich głosach wystarczy jedno wskazanie.": "requires a verbatim quotation from the material examined. With at least three conclusive votes, at least two models must identify it; with one or two such votes, one identification is sufficient.",
  "Zgoda modeli": "Model agreement",
  "to informacja dla czytelnika, nie dowód prawdy: modele mogą popełnić ten sam błąd.": "informs the reader, but does not prove truth: models can make the same mistake.",
  "odpowiedzi - cel dla każdego wpisu": "responses - the target for each post",
  "różne firmy": "different companies",
  "model polski wybierany jako pierwszy": "Polish model selected first",
  "Do każdego wpisu dobieramy modele różnych firm, zaczynając od polskiego. Gdy któryś nie odpowie, dołącza kolejny. Przy mniej niż 3 odpowiedziach diagnoza się nie ukazuje; niepełny skład opisujemy w jej ograniczeniach. Poniżej modele skonfigurowane do pracy w Konsylium.": "For each post we select models from different companies, starting with a Polish one. If one does not respond, another joins. With fewer than 3 responses, the diagnosis is not published; incomplete membership is described in its limitations. Below are the models configured to work in the Council.",
  "Rekrutacja do Konsylium": "Council recruitment",
  "Skład nie jest zamknięty. Co noc Rekruter Konsylium przegląda katalogi darmowych modeli i wybiera najwyżej jednego kandydata - pierwszeństwo ma model polski i firma, której jeszcze nie ma w składzie. Kandydat zdaje egzamin: ocenia te same wpisy polityków co Konsylium. Liczy się zgodność werdyktu i siły spinu z diagnozą końcową, cytowanie technik i polszczyzna. Obecni członkowie głosują, a przyjęty model musi przyjąć Kartę; role dostaje tylko wtedy, gdy wynik egzaminu je uzasadnia.": "Membership is open. Every night, the Council Recruiter reviews catalogues of free models and selects at most one candidate - priority goes to a Polish model and a company not yet represented. The candidate takes an exam: it assesses the same politicians' posts as the Council. The criteria are agreement with the final diagnosis on verdict and spin strength (0-100), quotations supporting techniques and quality of Polish. Current members vote, and an admitted model must accept the Charter; it receives roles only when its exam results justify them.",
  "Członek, który od trzech dni nie odpowiada (np. zniknął u dostawcy), zostaje zawieszony i wraca sam, gdy znów zacznie działać. Wszystkie decyzje zapisujemy poniżej. Do 7 października Rekruter działa w trybie próbnym: przyjęcia są rekomendacjami.": "A member that has not responded for three days (for example, because its provider has removed it) is suspended and returns automatically when it works again. We record all decisions below. Until 7 October, the Recruiter operates in trial mode: admissions are recommendations.",
  "Narzędzie": "Tool",
  "Do czego": "Purpose",
  "W systemie": "In the system",
  "Narzędzie obsługiwane przez system działa, gdy ma dostęp i wolny limit. Czy użyto go przy konkretnej diagnozie, widać w jej wynikach.": "A tool supported by the system operates when access and unused quota are available. A diagnosis's results show whether it was used for that analysis.",
  "Diagnoza wymaga co najmniej 3 odpowiedzi; skład bywa ograniczony, a część badań pominięta.": "A diagnosis requires at least 3 responses; membership may be limited and some checks omitted.",
  "Brak źródła oznacza brak weryfikacji, nie fałsz.": "No source means no verification, not falsehood.",
  "Brak recenzji albo jej negatywny wynik nie wstrzymuje automatycznie publikacji.": "The absence of a review or a negative review does not automatically prevent publication.",
  "Film dołączony do wpisu nie jest analizowany; wywiady mają osobny proces.": "Video attached to a post is not analysed; interviews follow a separate process.",
  "Zgoda modeli nie jest dowodem prawdy - mogą popełnić ten sam błąd.": "Model agreement does not prove truth - models can make the same mistake.",
  "12 zasad pracy i oświadczenia modeli": "12 working principles and model statements",
  "Metodologia": "Methodology",
  "selekcja, obliczenia i ograniczenia": "selection, calculations and limitations",
  "Zgłoś błąd": "Report an error",
  "link do diagnozy i źródła na kontakt@spin.clinic": "send the diagnosis link and sources to kontakt@spin.clinic",
  "Operator może wycofać diagnozę z publicznego widoku, ale nie zmienia jej treści, werdyktu ani siły.": "The operator can withdraw a diagnosis from public view, but does not change its content, verdict or strength.",
  "Bez sympatii i bez antypatii.": "No favour or disfavour.",
  "Nie ma znaczenia, kto mówi, z jakiej partii jest i czy jego poglądy komuś odpowiadają.": "It does not matter who is speaking, which party they belong to or whether anyone agrees with their views.",
  "Badamy słowa, nie ludzi.": "We examine words, not people.",
  "Diagnoza dotyczy konkretnej wypowiedzi: użytych technik, twierdzeń i słów. Nie oceniamy osoby, jej charakteru ani prawdomówności.": "A diagnosis concerns a specific statement: its techniques, claims and words. We do not assess the person, their character or their truthfulness.",
  "Ta sama miara dla obu stron.": "The same standard for both sides.",
  "Rządzący i opozycja są oceniani według tych samych kryteriów, tą samą skalą i tymi samymi narzędziami.": "The governing camp and the opposition are assessed using the same criteria, scale and tools.",
  "Nie zgadujemy intencji.": "We do not guess intentions.",
  "Nie przypisujemy autorowi zamiarów, których nie da się wykazać na podstawie tekstu.": "We do not attribute intentions to the author that cannot be demonstrated from the text.",
  "Każde twierdzenie ma status.": "Every claim has a status.",
  "Potwierdzone, sprzeczne ze źródłami, wprowadzające w błąd albo niezweryfikowane. Ocena faktu wymaga źródła. Grupa nazywana w zestawieniach opiniami obejmuje dziś także twierdzenia, których nie udało się sprawdzić.": "Supported, contradicted by sources, misleading or unverified. Assessing a factual claim requires a source. The group labelled 'opinions' in summaries currently also includes claims that could not be checked.",
  "Cytujemy wiernie.": "We quote faithfully.",
  "Nie wyolbrzymiamy ani nie łagodzimy słów autora. Streszczenie zachowuje siłę oryginału.": "We neither exaggerate nor soften the author's words. A summary preserves the force of the original.",
  "Mówimy, co zbadaliśmy.": "We state what we examined.",
  "Zakres analizy jest jawny (tekst, obraz, film) - czego nie zbadano, piszemy wprost.": "The scope of analysis is transparent (text, image, video) - we explicitly state what was not examined.",
  "Pokazujemy różnice zdań.": "We show disagreements.",
  "Jeśli członkowie Konsylium się nie zgadzają, widać to na diagnozie (zgodność werdyktu, rozrzut ocen).": "If Council members disagree, the diagnosis shows this (verdict agreement and the spread of scores).",
  "Opublikowanej diagnozy nie edytuje się ręcznie.": "A published diagnosis is not edited manually.",
  "Publikacja jest automatyczna. Człowiek może diagnozę tylko wycofać, nie zmienić jej treści.": "Publication is automatic. A human can only withdraw a diagnosis, not change its content.",
  "Prawo do korekty i odpowiedzi.": "The right to correction and reply.",
  "Każdy może zgłosić błąd lub przesłać odpowiedź. Dziś operator może ukryć całą diagnozę, zapisując datę i powód. Publiczny, datowany rejestr korekt i odpowiedzi jest zasadą docelową, jeszcze niewdrożoną.": "Anyone can report an error or submit a response. Currently, the operator can hide an entire diagnosis, recording the date and reason. A public, dated register of corrections and responses is a target principle that has not yet been implemented.",
  "Jawny skład.": "Transparent membership.",
  "Publikujemy, które modele i narzędzia, w jakich wersjach i rolach stawiają diagnozy.": "We publish which models and tools produce diagnoses, including their versions and roles.",
  "Niezależność od pieniędzy politycznych.": "Independence from political funding.",
  "spin.clinic nie przyjmuje darowizn od partii ani polityków; dane i raporty sprzedaje każdemu na tych samych warunkach, a ani wsparcie czytelników, ani klienci nie wpływają na diagnozy.": "spin.clinic does not accept donations from parties or politicians; it sells data and reports to everyone on the same terms, and neither readers' support nor clients influence diagnoses.",
  "Zasady": "Principles",
  "Stan przyjęcia Karty": "Charter acceptance status",
  "Karta Konsylium AI": "AI Council (Konsylium) Charter",
  "Zasady pracy modeli analizujących konkretne wypowiedzi. Wersja 1.1 doprecyzowuje statusy twierdzeń i obecne możliwości obsługi błędów.": "Working principles for models analysing specific statements. Version 1.1 clarifies claim statuses and the current options for handling errors.",
  "Nie deklarujemy, że każdy model przyjął Kartę. Rejestr pokazuje zapisane oświadczenia konkretnych wersji modeli, datę i wersję dokumentu, którego dotyczy odpowiedź. Brak oświadczenia oznacza oczekiwanie na jego zapisanie. Oświadczenie modelu nie jest podpisem ani poparciem jego twórcy lub dostawcy.": "We do not claim that every model has accepted the Charter. The register shows recorded statements by specific model versions, the date and the version of the document to which each response relates. No statement means it is awaiting recording. A model's statement is neither a signature nor an endorsement by its creator or provider.",
  "Pełny, aktualny wykaz jest w": "The full, current list is in the",
  "składzie Konsylium": "Council membership section",
  ". Oświadczenie dotyczące wcześniejszej wersji nie potwierdza przyjęcia wersji 1.1. Zasady są także częścią instrukcji analizy; sam wpis w rejestrze nie gwarantuje ich przestrzegania w każdym wyniku.": ". A statement about an earlier version does not confirm acceptance of version 1.1. The principles also form part of the analysis instructions; an entry in the register alone does not guarantee compliance in every result.",
  "Zgłoś błąd lub odpowiedź": "Report an error or submit a response",
  "Wyślij link do diagnozy, opis błędu i źródła na": "Send a link to the diagnosis, a description of the error and sources to",
  ". Operator może ukryć całą diagnozę, zapisując datę i powód; nie zmienia jej treści. Publiczna historia korekt i odpowiedzi pozostaje planem.": ". The operator can hide an entire diagnosis, recording the date and reason; its content is not changed. A public history of corrections and responses remains planned.",
  "Obecny sposób obsługi błędów": "How errors are currently handled",
  "Jak działa Konsylium AI": "How the AI Council (Konsylium) works",
  "Cytowanie diagnozy": "Citing a diagnosis",
  "Trwały link": "Permanent link",
  "Źródła i metodologia": "Sources and methodology",
  "Pilotaż spinek": "Thread pilot",
  "Zgoda na odczyt RSS": "Permission to read RSS",
  "Co pobieramy": "What we retrieve",
  "Tytuł, autora, datę publikacji, link i nazwę źródła.": "Title, author, publication date, link and source name.",
  "Skąd": "Where from",
  "Ze wskazanego kanału RSS albo wskazanych stron publicznych.": "The specified RSS feed or specified public pages.",
  "Tempo": "Frequency",
  "Co najmniej 3 sekundy między zapytaniami i uzgodniony limit dzienny.": "At least 3 seconds between requests and an agreed daily limit.",
  "Zakres": "Scope",
  "Bez pełnych tekstów, zdjęć ani kopii artykułów; nie trenujemy na nich modeli AI.": "No full texts, photos or copies of articles; we do not train AI models on them.",
  "Czytelnik": "Reader",
  "Widzi boks ze źródłem, a po kliknięciu trafia do oryginału.": "Sees a source card and reaches the original by clicking it.",
  "Zgoda": "Permission",
  "Brak odpowiedzi nie jest zgodą - źródło pozostaje wyłączone.": "No response is not permission - the source remains disabled.",
  "Rezygnacja": "Withdrawal",
  "Wystarczy wiadomość, a wyłączymy źródło.": "Send us a message and we will disable the source.",
  "DLA REDAKCJI": "FOR THE PRESS",
  "Korzystaj z analiz i źródeł": "Using analyses and sources",
  "Diagnoza Dr. Spina może być punktem wyjścia do pracy dziennikarskiej. Cytuj konkretną analizę, zaznacz udział AI i sprawdź materiał źródłowy.": "A diagnosis by Dr. Spin can be a starting point for journalistic work. Cite the specific analysis, acknowledge AI's involvement and check the source material.",
  "Jak cytować diagnozę": "How to cite a diagnosis",
  "Podaj nazwę spin.clinic, tytuł i datę diagnozy oraz jej bezpośredni adres. Zaznacz, że analizę przygotowało AI. Rozróżniaj ocenę techniki perswazji od statusu sprawdzanego twierdzenia; zachowaj kontekst cytatu i ograniczenia wyniku.": "Give the name spin.clinic, the diagnosis's title and date, and its direct URL. State that AI prepared the analysis. Distinguish the assessment of a persuasion technique from the status of a checked claim; preserve the quotation's context and the limitations of the result.",
  "Przykład zapisu: „Według analizy AI Dr. Spina w spin.clinic («[tytuł diagnozy]», [data diagnozy]) w tej wypowiedzi rozpoznano [technikę]. Źródło: [trwały adres diagnozy], dostęp: [data]”.": "Suggested wording: 'According to an AI analysis by Dr. Spin on spin.clinic ([diagnosis title], [diagnosis date]), [technique] was identified in this statement. Source: [permanent diagnosis URL], accessed: [date].'",
  "Wpis lub film spin.clinic w mediach społecznościowych jest skrótem analizy - przed cytowaniem otwórz pełną diagnozę i sprawdź materiał źródłowy. Uzupełnij pola danymi wybranej diagnozy. Jej siła 0-100 opisuje komunikat, nie osobę. Ocena AI nie zastępuje samodzielnej weryfikacji redakcyjnej.": "A spin.clinic social media post or video summarises an analysis - open the full diagnosis and check the source material before citing it. Fill in the fields using the chosen diagnosis. Its spin strength (0-100) describes the message, not the person. An AI assessment does not replace a newsroom's independent verification.",
  "Otwórz konkretną diagnozę z": "Open a specific diagnosis from the",
  "archiwum": "archive",
  "i skopiuj adres jej strony:": "and copy its page URL:",
  ". Zachowuje on identyfikator analizy; adres strony głównej lub widok „spin dnia” nie wskazuje stale tego samego materiału.": ". This retains the analysis identifier; the homepage URL or 'spin of the day' view does not always point to the same material.",
  "Zapisz również datę dostępu. Po wycofaniu diagnozy albo utracie dostępności wpisu treść może przestać być publicznie widoczna. Stały identyfikator nie jest gwarancją wieczystego dostępu.": "Also record the access date. If a diagnosis is withdrawn or the post becomes unavailable, the content may no longer be publicly visible. A permanent identifier does not guarantee perpetual access.",
  "Przy diagnozie są wpis wejściowy, cytaty i źródła do sprawdzanych twierdzeń. Otwórz oryginały i sprawdź, co rzeczywiście potwierdzają.": "The diagnosis includes the original post, quotations and sources for checked claims. Open the originals and check what they actually support.",
  "Katalog źródeł": "Source catalogue",
  "to osobny wykaz; nie jest listą dowodów użytych w każdej diagnozie.": "is a separate list; it is not a list of evidence used in every diagnosis.",
  "Aktualna metodologia": "The current methodology",
  "wyjaśnia sposób obliczeń i ograniczenia.": "explains calculations and limitations.",
  "Konsylium AI": "AI Council (Konsylium)",
  "pokazuje aktualny skład, a uczestników konkretnej analizy sprawdzisz przy jej wyniku.": "shows current membership; the participants in a specific analysis are listed with its result.",
  "Zasady wycofania diagnozy": "Rules for withdrawing a diagnosis",
  "Kontakt z projektem": "Contact the project",
  "Współpraca i pytania mediów:": "Collaboration and media enquiries:",
  ". Zgłoszenia błędów wraz z linkiem i dowodami:": ". Error reports with a link and evidence:",
  "dane operatora": "operator details",
  "Spinki podpisane przez redakcje": "Spinki signed by newsrooms",
  "Każdy może ułożyć spinkę z konta: boksy z materiałami, połączenia i wyjaśnienie w podtytule. Redakcje i dziennikarze mogą prowadzić spinki podpisane nazwiskiem i redakcją. Ocenia je ta sama miara co spinki Dr. Spina i czytelników.": "Anyone with an account can build a spinka: boxes with material, connections and an explanation in the subtitle. Newsrooms and journalists can run spinki signed with their name and outlet. They are rated by the same standard as spinki by Dr. Spin and by readers.",
  "W sprawie spinek podpisanych przez redakcję napisz na": "About spinki signed by your newsroom, write to",
  "Chętnie uwzględnimy wymagany sposób oznaczania źródła i limity techniczne. Kontakt w sprawie zgody:": "We are happy to accommodate required source attribution and technical limits. For permission enquiries, contact:",
  "Diagnozy najsilniejszych spinów i wątki z uzasadnieniem.": "Diagnoses of the strongest spin and threads explaining the findings. (in Polish)",
  "Filmy z wybranych diagnoz i odnośniki do pełnych analiz.": "Videos based on selected diagnoses and links to full analyses. (in Polish)",
  "Krótkie filmy z diagnoz i satyryczny „Przekaz dnia”.": "Short videos based on diagnoses and the satirical Message of the day. (in Polish)",
  "Shorts: „Przekaz dnia - co usłyszało stado?” i filmy z diagnoz.": "Shorts: Message of the day - what did the herd hear? And videos based on diagnoses. (in Polish)",
  "Karty diagnoz z linkiem do pełnej analizy.": "Diagnosis cards with a link to the full analysis. (in Polish)",
  "Zgodność z SemEval 2023": "Alignment with SemEval 2023",
  "to międzynarodowe zadanie badawcze, którego podzadanie 3 dotyczy rozpoznawania 23 technik perswazji w 6 grupach, także w tekstach po polsku. Poniższe przypisanie jest nasze i orientacyjne. Kategorie dotyczące rzetelności danych, faktów i wnioskowania wykraczają poza ten katalog perswazji językowej. Przypisanie nie oznacza walidacji skuteczności naszego systemu w SemEval.": "is an international research task whose subtask 3 covers detecting 23 persuasion techniques in 6 groups, including in Polish texts. The mapping below is our own and indicative. Categories about the reliability of data, facts and reasoning go beyond this catalogue of linguistic persuasion. The mapping does not mean that our system has been validated in SemEval.",
  "Nasza kategoria": "Our category",
  "Odpowiednik SemEval": "SemEval equivalent",
  "brak odpowiednika": "no equivalent",
  "Słowa nacechowane (osobny moduł)": "Loaded words (separate module)",
  "Techniki SemEval, których nie rozpoznajemy osobno:": "SemEval techniques we do not detect separately:",
  "Słomiany człowiek": "Straw man",
  "Inne": "Other",
  "Dane i raporty": "Data and reports",
  "Dane i raporty dla firm i instytucji": "Data and reports for companies and institutions",
  "Z danych, które zbieramy i analizujemy, przygotowujemy zestawienia na zamówienie:": "From the data we collect and analyse, we prepare reports on request:",
  "powiadomienia o nowych wpisach i diagnozach wskazanych polityków,": "alerts on new posts and diagnoses of selected politicians,",
  "tygodniowy raport przekazu rządzących i opozycji,": "a weekly report on the messaging of the government and the opposition,",
  "monitoring tematu lub branży: projekty ustaw, wypowiedzi polityków, sygnały lobbingu,": "monitoring of a topic or sector: bills, politicians' statements, lobbying signals,",
  "zestawienie wypowiedzi polityka: historia, zmiany stanowiska, zgodność z głosowaniami,": "a politician's statement record: history, changes of position, consistency with votes,",
  "dane do badań naukowych.": "data for academic research.",
  "Jedna oferta dla wszystkich: te same produkty i warunki bez względu na obóz polityczny. Klient nie ma wpływu na metodę, diagnozy ani treści serwisu. Sprzedajemy nasze analizy, nie treści cudzych wpisów.": "One offer for everyone: the same products and terms regardless of political camp. Clients have no influence over the method, diagnoses or site content. We sell our analyses, not the content of other people's posts.",
  "Zapytaj o dane": "Ask about data",
} as const;
