# Generated by Django 5.1.15 on 2026-09-07 19:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date'], 'permissions': [('access_premium', 'Dostęp do materiałów premium')], 'verbose_name': 'artykuł', 'verbose_name_plural': 'artykuły'},
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='news_articl_publish_68b4ca_idx',
            old_name='news_articl_publish_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='news_articl_title_dca5f8_idx',
            old_name='news_articl_title_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Redakcja', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='retweets_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='scraped_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='article',
            name='tweet_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='source',
            name='last_scraped',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='last_tweet_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='source',
            name='scrape_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='source',
            name='scrape_frequency_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='source',
            name='total_articles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('statement', 'Oświadczenie'), ('mention', 'Wzmianka'), ('video', 'Wideo'), ('sponsored', 'Sponsorowane'), ('article', 'Artykuł'), ('tweet', 'Tweet'), ('factcheck', 'Fact-check'), ('context', 'Kontekst'), ('opinion', 'Opinia')], db_index=True, default='article', max_length=32, verbose_name='kategoria'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('portal', 'Portal'), ('newspaper', 'Prasa'), ('politician', 'Polityk'), ('institution', 'Instytucja'), ('rss', 'RSS'), ('twitter', 'Twitter'), ('newsapi', 'NewsAPI'), ('gdelt', 'GDELT'), ('editorial', 'Redakcja')], default='rss', max_length=32, verbose_name='typ źródła'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_type',
            field=models.CharField(choices=[('sponsored', 'Sponsorowane'), ('factcheck', 'Fact-check'), ('context', 'Kontekst')], db_index=True, max_length=32, verbose_name='typ wątku'),
        ),
    ]
