# Generated by Django 5.1.15 on 2026-09-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_title_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='rss_url',
            field=models.URLField(blank=True, max_length=4096, verbose_name='adres RSS'),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(max_length=4096, unique=True, verbose_name='adres URL'),
        ),
    ]
