# Generated by Django 5.1.15 on 2026-09-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_source_url_lengths'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date'], 'verbose_name': 'artykuł', 'verbose_name_plural': 'artykuły'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_premium',
        ),
        migrations.AddField(
            model_name='article',
            name='category_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='discovered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='evidence_note',
            field=models.TextField(blank=True, help_text='Jak redakcja sprawdziła pochodzenie lub treść materiału.'),
        ),
        migrations.AddField(
            model_name='article',
            name='ingestion_method',
            field=models.CharField(choices=[('manual', 'Redakcja'), ('rss', 'RSS'), ('gdelt', 'GDELT'), ('newsapi', 'NewsAPI'), ('x', 'X')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='source',
            name='last_error',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('reportage', 'Reportaż'), ('advertisement', 'Reklama'), ('other', 'Inne / nieustalona kategoria'), ('statement', 'Oświadczenie'), ('mention', 'Wzmianka'), ('video', 'Wideo'), ('sponsored', 'Sponsorowane'), ('article', 'Artykuł'), ('tweet', 'Tweet'), ('factcheck', 'Fact-check'), ('context', 'Kontekst'), ('opinion', 'Opinia')], db_index=True, default='article', max_length=32, verbose_name='kategoria'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='data publikacji'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_type',
            field=models.CharField(choices=[('sponsored', 'Sponsorowane'), ('factcheck', 'Fact-check'), ('context', 'Kontekst')], db_index=True, default='context', max_length=32, verbose_name='typ wątku'),
        ),
    ]
