# Generated by Django 5.1.15 on 2026-09-08 00:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_open_portal_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_precision',
            field=models.CharField(choices=[('time', 'Data i czas'), ('day', 'Tylko dzień')], default='time', max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('voting', 'Głosowanie Sejmu'), ('legislation', 'Akt prawny / obwieszczenie'), ('parliamentary_print', 'Druk sejmowy'), ('reportage', 'Reportaż'), ('advertisement', 'Reklama'), ('other', 'Inne / nieustalona kategoria'), ('statement', 'Oświadczenie'), ('mention', 'Wzmianka'), ('video', 'Wideo'), ('sponsored', 'Sponsorowane'), ('article', 'Artykuł'), ('tweet', 'Tweet'), ('factcheck', 'Fact-check'), ('context', 'Kontekst'), ('opinion', 'Opinia')], db_index=True, default='article', max_length=32, verbose_name='kategoria'),
        ),
        migrations.CreateModel(
            name='ParliamentaryVoting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.PositiveSmallIntegerField()),
                ('sitting', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('motion', models.TextField()),
                ('kind', models.CharField(max_length=40)),
                ('counts', models.JSONField(default=dict)),
                ('options', models.JSONField(default=list)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='news.article')),
            ],
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_id', models.PositiveIntegerField()),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('club', models.CharField(blank=True, max_length=100)),
                ('vote', models.CharField(max_length=30)),
                ('list_votes', models.JSONField(default=dict)),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='news.parliamentaryvoting')),
            ],
            options={
                'ordering': ['name', 'mp_id'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(help_text='Fraza wyszukiwania powiązana ze źródłem.', max_length=200)),
                ('source_url', models.URLField(max_length=1024)),
                ('explanation', models.TextField(help_text='Dlaczego źródło uzasadnia powiązanie z tym materiałem.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='news.article')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('article', 'phrase', 'source_url'), name='unique_evidence_link')],
            },
        ),
        migrations.CreateModel(
            name='OfficialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('sejm', 'Sejm'), ('eli', 'ELI')], max_length=20)),
                ('external_id', models.CharField(max_length=100)),
                ('api_url', models.URLField(max_length=1024)),
                ('raw_data', models.JSONField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official_record', to='news.article')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_official_record')],
            },
        ),
        migrations.AddConstraint(
            model_name='parliamentaryvoting',
            constraint=models.UniqueConstraint(fields=('term', 'sitting', 'number'), name='unique_sejm_voting'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.UniqueConstraint(fields=('voting', 'mp_id'), name='unique_mp_ballot'),
        ),
    ]
