# Generated by Django 5.1.15 on 2026-09-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_date_precision_alter_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ingestion_method',
            field=models.CharField(choices=[('manual', 'Redakcja'), ('rss', 'RSS'), ('gdelt', 'GDELT'), ('newsapi', 'NewsAPI'), ('x', 'X'), ('sejm', 'API Sejmu'), ('eli', 'ELI')], default='manual', max_length=20),
        ),
    ]
