# Generated by Django 5.1.15 on 2026-09-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_article_ingestion_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('last_started', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('imported', models.PositiveIntegerField(default=0)),
                ('cursor', models.JSONField(default=dict)),
            ],
        ),
    ]
