# Generated by Django 5.1.15 on 2026-09-08 00:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_importstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField()),
                ('fetched_at', models.DateTimeField()),
                ('replaced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='news.officialrecord')),
            ],
            options={
                'ordering': ['-replaced_at'],
            },
        ),
    ]
