# Generated by Django 5.1.15 on 2026-09-08 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_officialrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='threaditem',
            name='external_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='threaditem',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_items', to='news.article', verbose_name='artykuł'),
        ),
    ]
