# Generated by Django 5.1.15 on 2026-09-08 14:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_media_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024, unique=True)),
                ('kind', models.CharField(choices=[('sitemap', 'Sitemap'), ('page', 'Strona')], max_length=10)),
                ('status', models.CharField(db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_at', models.DateTimeField(null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_jobs', to='news.source')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('method', models.CharField(default='publisher_jsonld_articleBody', max_length=50)),
                ('status', models.CharField(default='metadata_only', max_length=30)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_sha256', models.CharField(max_length=64)),
                ('source_url', models.URLField(max_length=1024)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='news.article')),
            ],
        ),
    ]
