# Generated by Django 5.1.15 on 2026-09-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_archivejob_articlecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ingestion_method',
            field=models.CharField(choices=[('manual', 'Redakcja'), ('rss', 'RSS'), ('gdelt', 'GDELT'), ('newsapi', 'NewsAPI'), ('x', 'X'), ('sejm', 'API Sejmu'), ('eli', 'ELI'), ('archive', 'Archiwum wydawcy'), ('youtube', 'YouTube')], default='manual', max_length=20),
        ),
    ]
