# Generated by Django 5.1.15 on 2026-09-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_article_ingestion_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='last_attempted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
