# Generated by Django 5.1.15 on 2026-09-08 21:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_source_last_attempted'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('evidence', models.JSONField(default=dict)),
                ('first_detected', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_issues', to='news.article')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('article', 'code'), name='unique_article_quality_issue')],
            },
        ),
    ]
