# Generated by Django 5.1.15 on 2026-09-09 13:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_qualityissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResearchCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(null=True)),
                ('mode', models.CharField(choices=[('context', 'Context'), ('verify', 'Verify')], max_length=12)),
                ('model', models.CharField(max_length=120)),
                ('response_model', models.CharField(max_length=120, null=True)),
                ('status', models.CharField(db_index=True, default='started', max_length=32)),
                ('provider_status', models.CharField(max_length=20, null=True)),
                ('http_status', models.PositiveSmallIntegerField(null=True)),
                ('input_tokens', models.PositiveBigIntegerField(null=True)),
                ('output_tokens', models.PositiveBigIntegerField(null=True)),
                ('web_search_calls', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ['-started_at', '-pk'],
            },
        ),
    ]
