# Generated by Django 5.1.15 on 2026-09-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_source_seed_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='article', name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Hasła jawnie podane przez wydawcę; nie są oceną treści.'),
        ),
        migrations.AddField(
            model_name='thread',
            name='editorial_slot',
            field=models.CharField(blank=True, choices=[('', 'Pozostałe nitki'), ('government', 'Przekaz dnia obozu rządzącego'), ('opposition', 'Przekaz dnia opozycji')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('voting', 'Głosowanie Sejmu'), ('legislation', 'Akt prawny / obwieszczenie'), ('parliamentary_print', 'Druk sejmowy'), ('reportage', 'Reportaż'), ('interview', 'Wywiad'), ('podcast', 'Podcast'), ('document', 'Dokument urzędowy'), ('advertisement', 'Reklama'), ('other', 'Inne / nieustalona kategoria'), ('statement', 'Komunikat / oświadczenie'), ('mention', 'Wzmianka'), ('video', 'Film'), ('sponsored', 'Sponsorowane'), ('article', 'Artykuł'), ('tweet', 'Tweet'), ('factcheck', 'Fact-check'), ('context', 'Kontekst'), ('opinion', 'Opinia')], db_index=True, default='article', max_length=32, verbose_name='kategoria'),
        ),
    ]
