# Generated by Django 5.1.15 on 2026-09-09 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_personalized_portal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarity', models.CharField(choices=[('positive', 'Pozytywny'), ('negative', 'Negatywny')], max_length=8)),
                ('body', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='news.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_opinions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'article'), name='one_opinion_per_user_article'), models.CheckConstraint(condition=models.Q(('polarity__in', ['positive', 'negative'])), name='opinion_valid_polarity')],
            },
        ),
        migrations.CreateModel(
            name='SavedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('query', models.CharField(max_length=200)),
                ('categories', models.JSONField(default=list)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('slot', models.PositiveSmallIntegerField(editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_topics', to=settings.AUTH_USER_MODEL)),
                ('sources', models.ManyToManyField(blank=True, to='news.source')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'slot'), name='unique_topic_owner_slot'), models.CheckConstraint(condition=models.Q(('slot__gte', 0), ('slot__lt', 10)), name='topic_slot_max_ten')],
            },
        ),
    ]
