# Generated by Django 5.1.15 on 2026-09-09 19:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_public_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=19, unique=True, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{0,18}$', 'Podaj numeryczny identyfikator X.')])),
                ('handle', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]{1,15}$', 'Podaj nazwę konta X bez @.')])),
                ('display_name', models.CharField(max_length=150)),
                ('camp', models.CharField(choices=[('government', 'Obóz rządzący'), ('opposition', 'Opozycja')], max_length=12)),
                ('confirmation_url', models.URLField(blank=True, help_text='Publiczne źródło potwierdzające tożsamość konta i przyjętą klasyfikację.', max_length=1024)),
                ('confirmation_note', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_fingerprint', models.CharField(blank=True, editable=False, max_length=64)),
                ('enabled', models.BooleanField(default=False)),
                ('poll_interval_minutes', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('poll_cursor', models.JSONField(blank=True, default=dict, editable=False)),
                ('next_poll_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('last_polled_at', models.DateTimeField(editable=False, null=True)),
                ('last_error', models.CharField(blank=True, editable=False, max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_political_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=19, unique=True, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{0,18}$', 'Podaj numeryczny identyfikator X.')])),
                ('url', models.URLField(max_length=1024)),
                ('text', models.TextField()),
                ('published_at', models.DateTimeField(db_index=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_data', models.JSONField(default=dict)),
                ('author_data', models.JSONField(default=dict)),
                ('media', models.JSONField(default=list)),
                ('response_sha256', models.CharField(max_length=64)),
                ('camp_at_collection', models.CharField(choices=[('government', 'Obóz rządzący'), ('opposition', 'Opozycja')], max_length=12)),
                ('available', models.BooleanField(db_index=True, default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='news.politicalaccount')),
            ],
            options={
                'ordering': ['-published_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PoliticalDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp', models.CharField(choices=[('government', 'Obóz rządzący'), ('opposition', 'Opozycja')], max_length=12)),
                ('day', models.DateField()),
                ('title', models.CharField(max_length=250)),
                ('origin', models.CharField(choices=[('editorial_selection', 'Wybór redakcji'), ('ai_proposal', 'Propozycja AI')], default='editorial_selection', max_length=20)),
                ('proposed_items', models.JSONField(default=list, help_text='Szkic powiązań do sprawdzenia; nie są rekordami źródłowymi.')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_review', 'Do przeglądu'), ('approved', 'Zatwierdzony szkic'), ('rejected', 'Odrzucony')], db_index=True, default='pending_review', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='political_drafts_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='political_drafts_reviewed', to=settings.AUTH_USER_MODEL)),
                ('posts', models.ManyToManyField(related_name='drafts', to='news.politicalpost')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PoliticalRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(null=True)),
                ('reserved_posts', models.PositiveSmallIntegerField()),
                ('reserved_usd', models.DecimalField(decimal_places=6, max_digits=12)),
                ('returned_posts', models.PositiveSmallIntegerField(null=True)),
                ('status', models.CharField(default='reserved', max_length=32)),
                ('http_status', models.PositiveSmallIntegerField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_reads', to='news.politicalaccount')),
            ],
            options={
                'ordering': ['-started_at', '-pk'],
            },
        ),
    ]
