# Generated by Django 5.1.15 on 2026-09-09 20:12

from django.conf import settings
from django.db import migrations, models


def prepare_roles_and_legacy_sponsorship(apps, schema_editor):
    alias = schema_editor.connection.alias
    apps.get_model('auth', 'Group').objects.using(alias).get_or_create(name='journalists')
    threads = apps.get_model('news', 'Thread').objects.using(alias).filter(thread_type='sponsored')
    threads.update(is_sponsored=True)
    # A legacy type proves sponsorship, but does not identify a sponsor.
    # Keep that fact and ask staff to complete the label before publication.
    threads.filter(sponsor_name='').update(published=False, is_featured=False)


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_profiles_topics_favorites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_sponsored',
            field=models.BooleanField(default=False, verbose_name='materiał sponsorowany'),
        ),
        migrations.AddField(
            model_name='thread',
            name='sponsor_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='nazwa sponsora'),
        ),
        migrations.RunPython(prepare_roles_and_legacy_sponsorship, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='thread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published', True), _negated=True), models.Q(models.Q(('is_sponsored', True), _negated=True), models.Q(('thread_type', 'sponsored'), _negated=True)), models.Q(('sponsor_name', ''), _negated=True), _connector='OR'), name='published_sponsored_thread_has_name'),
        ),
    ]
