# Generated by Django 5.1.15 on 2026-09-14 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_threadopinion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1024, verbose_name='adres źródłowy')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='czas pobrania')),
                ('content_sha256', models.CharField(max_length=64, verbose_name='hash SHA-256 treści/obrazu')),
                ('artifact_type', models.CharField(choices=[('html', 'Zrzut HTML'), ('image', 'Obraz / zrzut ekranu'), ('pdf', 'PDF'), ('other', 'Inny')], max_length=16, verbose_name='typ artefaktu')),
                ('parser_version', models.CharField(max_length=60, verbose_name='wersja parsera')),
                ('consent_status', models.CharField(choices=[('unknown', 'Nieustalone'), ('allowed', 'Dozwolone przez wydawcę lub zgodę'), ('restricted', 'Ograniczone — wyłącznie wewnętrzny dowód'), ('denied', 'Odmówione — artefakt do usunięcia')], default='unknown', max_length=16, verbose_name='stan zgody/licencji')),
                ('storage_key', models.CharField(db_index=True, help_text='Odniesienie do prywatnego backendu (news.snapshot_storage). Nigdy publiczny URL ani binaria. Klucz jest wyznaczony z hasha treści, więc kolejne obserwacje tej samej treści mogą go współdzielić.', max_length=512, verbose_name='prywatny klucz storage')),
                ('retention_policy', models.CharField(choices=[('evidence_hold', 'Zatrzymane jako dowód do decyzji redakcji'), ('temporary', 'Tymczasowe, do automatycznego usunięcia'), ('indefinite', 'Bezterminowe (wymaga okresowego przeglądu)')], default='evidence_hold', max_length=16, verbose_name='polityka retencji')),
                ('retention_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='retencja do')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_snapshots', to='news.article', verbose_name='box')),
            ],
            options={
                'verbose_name': 'prywatny snapshot dowodowy',
                'verbose_name_plural': 'prywatne snapshoty dowodowe',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
