# Generated by Django 5.1.15 on 2026-09-15 00:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0034_sourceaccessinstruction_valid_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_version', models.PositiveIntegerField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('api', 'API'), ('rss', 'RSS / Atom'), ('export', 'Eksport danych'), ('oai_pmh', 'OAI-PMH'), ('sitemap', 'Sitemap'), ('html', 'Jawnie dozwolony HTML')], max_length=16)),
                ('requested_kind', models.CharField(choices=[('feed', 'Feed'), ('sitemap', 'Sitemap'), ('page', 'Strona'), ('api_record', 'Rekord API'), ('robots', 'robots.txt'), ('probe', 'Próba audytowa')], max_length=16)),
                ('url_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('url_host', models.CharField(db_index=True, max_length=255)),
                ('attempted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('outcome', models.CharField(choices=[('refused_no_instruction', 'Brak instrukcji'), ('refused_expired', 'Instrukcja wygasła'), ('refused_suspended', 'Instrukcja wstrzymana'), ('refused_scope_mismatch', 'Poza zakresem instrukcji'), ('blocked_robots', 'Zablokowane przez robots'), ('ok', 'Sukces'), ('http_error', 'Błąd HTTP'), ('network_error', 'Błąd sieci'), ('redirected', 'Przekierowanie')], db_index=True, max_length=32)),
                ('network_started', models.BooleanField(default=False)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bytes_received', models.PositiveBigIntegerField(default=0)),
                ('response_sha256', models.CharField(blank=True, max_length=64)),
                ('redirect_target_host', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('instruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fetch_attempts', to='news.sourceaccessinstruction')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fetch_attempts', to='news.source')),
            ],
            options={
                'ordering': ['-attempted_at', '-id'],
                'indexes': [models.Index(fields=['source', '-attempted_at'], name='news_fetcha_source__a622fa_idx')],
            },
        ),
    ]
