# Generated by Django 5.1.15 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_fetch_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchattempt',
            name='adapter_revision',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='fetchattempt',
            name='request_user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fetchattempt',
            name='transport',
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
