# Generated by Django 5.1.15 on 2026-09-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0036_fetchattempt_transport_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialrecord',
            name='fetch_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name='official_records', to='news.fetchattempt'),
        ),
    ]
