# Generated by Django 5.1.15 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0037_officialrecord_fetch_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchattempt',
            name='decision_basis',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
