# Generated by Django 5.1.15 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0038_fetchattempt_decision_basis'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, unique=True)),
                ('locked_by', models.CharField(max_length=96)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
