# Generated by Django 5.1.15 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0039_hostgate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchattempt',
            name='outcome',
            field=models.CharField(choices=[('refused_no_instruction', 'Brak instrukcji'), ('refused_expired', 'Instrukcja wygasła'), ('refused_suspended', 'Instrukcja wstrzymana'), ('refused_scope_mismatch', 'Poza zakresem instrukcji'), ('rate_limit_preemptive', 'Limit hosta przed siecią'), ('blocked_robots', 'Zablokowane przez robots'), ('ok', 'Sukces'), ('http_error', 'Błąd HTTP'), ('network_error', 'Błąd sieci'), ('redirected', 'Przekierowanie')], db_index=True, max_length=32),
        ),
    ]
