# Generated by Django 5.1.15 on 2026-09-15

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0040_fetchattempt_rate_limit_preemptive'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostgate',
            name='next_allowed_at',
            field=models.DateTimeField(db_index=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
