# Generated by Django 5.1.15 on 2026-09-15

import uuid

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0042_fetchattempt_request_id_and_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_host', models.CharField(db_index=True, max_length=255)),
                ('url_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('state', models.CharField(choices=[('reserved', 'Zarezerwowana'), ('closed', 'Zamknięta'), ('abandoned', 'Nieukończona')], db_index=True, default='reserved', max_length=16)),
                ('reserved_at', models.DateTimeField(db_index=True, default=timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('instruction', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='fetch_requests', to='news.sourceaccessinstruction')),
                ('source', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='fetch_requests', to='news.source')),
            ],
        ),
    ]
