# Generated by Django 5.1.15 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0044_fetchattempt_abandoned'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fetchrequest',
            constraint=models.CheckConstraint(
                condition=(
                    (models.Q(('state', 'reserved'), ('closed_at__isnull', True)))
                    | (~models.Q(('state', 'reserved')) & models.Q(('closed_at__isnull', False)))
                ),
                name='fetch_request_state_matches_closed_at',
            ),
        ),
    ]
