# Generated by Django 5.1.15 on 2026-09-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("news", "0045_fetchrequest_state_closed_at")]

    operations = [
        migrations.AlterField(
            model_name="evidencesnapshot",
            name="article",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence_snapshots", to="news.article", verbose_name="box"),
        ),
        migrations.AddField(
            model_name="evidencesnapshot",
            name="fetch_attempt",
            field=models.ForeignKey(blank=True, help_text="Niezmienny dowód konkretnego pobrania. Starsze rekordy mogą go nie mieć.",
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="evidence_snapshots",
                to="news.fetchattempt", verbose_name="potwierdzona próba pobrania"),
        ),
    ]
