# Generated by Django 5.1.15 on 2026-09-15 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0046_evidencesnapshot_fetch_attempt_protect_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchattempt',
            name='request_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
