# Generated by Django 5.1.15 on 2026-09-15 20:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0048_sourceaccessinstruction_allowed_path_patterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceaccessinstruction',
            name='daily_request_cap',
            field=models.PositiveIntegerField(default=0, help_text='Twardy dzienny limit żądań tej karty; 0 oznacza brak dostępu automatycznego.'),
        ),
        migrations.AlterField(
            model_name='fetchattempt',
            name='outcome',
            field=models.CharField(choices=[('reserved', 'Audyt zapisany przed siecią'), ('abandoned', 'Nieukończona próba'), ('refused_no_instruction', 'Brak instrukcji'), ('refused_expired', 'Instrukcja wygasła'), ('refused_suspended', 'Instrukcja wstrzymana'), ('refused_scope_mismatch', 'Poza zakresem instrukcji'), ('rate_limit_preemptive', 'Limit hosta przed siecią'), ('daily_limit_preemptive', 'Dzienny limit źródła przed siecią'), ('blocked_robots', 'Zablokowane przez robots'), ('ok', 'Sukces'), ('http_error', 'Błąd HTTP'), ('network_error', 'Błąd sieci'), ('redirected', 'Przekierowanie')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='SourceDailyFetchBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today)),
                ('used', models.PositiveIntegerField(default=0)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_fetch_budgets', to='news.sourceaccessinstruction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('instruction', 'day'), name='unique_source_instruction_daily_fetch_budget')],
            },
        ),
    ]
