# Generated by Django 5.1.15 on 2026-09-23 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0059_core_state_account_candidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialhandleevidence',
            name='evidence_url',
            field=models.URLField(help_text='Oficjalny profil, na którym znaleziono link.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='socialhandleevidence',
            name='extracted_url',
            field=models.URLField(help_text='Bezpośredni link X/Twitter znaleziony na oficjalnej stronie.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='socialhandleevidence',
            name='handle',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]{1,15}$', 'Podaj nazwę konta X bez @.')]),
        ),
    ]
