# Generated by Django 5.1.15 on 2026-09-25 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0075_officialvideochannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicfigure',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='Potwierdzone przez redakcję połączenie z profilem tej samej osoby. Połączony wpis pozostaje archiwalny także po synchronizacji rosterów; jego role trafiają do profilu docelowego.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_profiles', to='news.publicfigure'),
        ),
    ]
