# Generated by Django 5.1.15 on 2026-09-25 22:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0077_articlechangeevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_review', 'Czeka na zatwierdzenie'), ('approved', 'Zatwierdzona'), ('rejected', 'Odrzucona'), ('failed', 'Błąd analizy'), ('not_applicable', 'Bez treści do oceny')], db_index=True, default='pending_review', max_length=16)),
                ('verdict', models.CharField(blank=True, choices=[('spin', 'Spin'), ('partial', 'Częściowy spin'), ('no_spin', 'Bez spinu'), ('unclear', 'Nie da się ocenić')], max_length=12)),
                ('intensity', models.PositiveSmallIntegerField(default=0, help_text='Siła spinu 0–100 według modelu.')),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('analysis', models.TextField(blank=True)),
                ('techniques', models.JSONField(blank=True, default=list)),
                ('claims', models.JSONField(blank=True, default=list)),
                ('limitations', models.TextField(blank=True)),
                ('triage', models.JSONField(blank=True, default=dict, help_text='Wynik wstępnej selekcji (czy post zawiera treść do oceny).')),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('prompt_version', models.CharField(blank=True, max_length=16)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, help_text='Ukrycie po zgłoszeniu prawnym. Treść diagnozy pozostaje bez zmian.', null=True)),
                ('hidden_reason', models.CharField(blank=True, max_length=240)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spin_diagnosis', to='news.politicalpost')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'diagnoza spinu',
                'verbose_name_plural': 'diagnozy spinu',
                'ordering': ['-post__published_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ClinicDailyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('camp', models.CharField(choices=[('government', 'Obóz rządzący'), ('opposition', 'Opozycja')], max_length=12)),
                ('message', models.TextField()),
                ('themes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending_review', 'Czeka na zatwierdzenie'), ('approved', 'Zatwierdzona'), ('rejected', 'Odrzucona'), ('failed', 'Błąd analizy'), ('not_applicable', 'Bez treści do oceny')], db_index=True, default='pending_review', max_length=16)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('prompt_version', models.CharField(blank=True, max_length=16)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('posts', models.ManyToManyField(blank=True, related_name='clinic_daily_messages', to='news.politicalpost')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'przekaz dnia',
                'verbose_name_plural': 'przekazy dnia',
                'ordering': ['-day', 'camp'],
                'constraints': [models.UniqueConstraint(fields=('day', 'camp'), name='one_clinic_message_per_day_camp')],
            },
        ),
        migrations.CreateModel(
            name='SpinOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarity', models.CharField(choices=[('positive', 'Trafna diagnoza'), ('negative', 'Nietrafna diagnoza')], max_length=8)),
                ('body', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='news.spindiagnosis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_opinions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'diagnosis'), name='one_opinion_per_user_spin'), models.CheckConstraint(condition=models.Q(('polarity__in', ['positive', 'negative'])), name='spin_opinion_valid_polarity')],
            },
        ),
        migrations.CreateModel(
            name='XAccountSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('handle', models.CharField(max_length=15)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('new', 'Nowa'), ('accepted', 'Przyjęta'), ('rejected', 'Odrzucona')], db_index=True, default='new', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('public_figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x_account_suggestions', to='news.publicfigure')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sugestia konta X',
                'verbose_name_plural': 'sugestie kont X',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('public_figure', 'handle'), name='one_suggestion_per_figure_handle')],
            },
        ),
    ]
