# Generated by Django 5.1.15 on 2026-09-25 22:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0078_clinic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityThreadOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarity', models.CharField(choices=[('positive', 'Przydatna'), ('negative', 'Nieprzydatna')], max_length=8)),
                ('body', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommunityThreadReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Naruszenie zasad'), ('privacy', 'Dane prywatne'), ('copyright', 'Naruszenie praw autorskich'), ('other', 'Inne')], max_length=16)),
                ('details', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('new', 'Nowe'), ('resolved', 'Rozpatrzone')], db_index=True, default='new', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'zgłoszenie nitki',
                'verbose_name_plural': 'zgłoszenia nitek',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='personalcontextthread',
            name='hidden_at',
            field=models.DateTimeField(blank=True, help_text='Ukrycie przez zespół po zgłoszeniu.', null=True),
        ),
        migrations.AddField(
            model_name='personalcontextthread',
            name='hidden_reason',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='personalcontextthread',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='personalcontextthread',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalcontextthreaditem',
            name='note',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
        migrations.AlterField(
            model_name='personalcontextthreaditem',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_context_thread_items', to='news.article'),
        ),
        migrations.CreateModel(
            name='CommunityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_url', models.URLField(max_length=1024, unique=True)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=300)),
                ('title_origin', models.CharField(choices=[('publisher', 'Tytuł z metadanych strony'), ('reader', 'Tytuł podany przez czytelnika')], default='reader', max_length=10)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'link czytelnika',
                'verbose_name_plural': 'linki czytelników',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='personalcontextthreaditem',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_items', to='news.communitylink'),
        ),
        migrations.AddConstraint(
            model_name='personalcontextthreaditem',
            constraint=models.UniqueConstraint(fields=('thread', 'link'), name='unique_personal_context_thread_link'),
        ),
        migrations.AddConstraint(
            model_name='personalcontextthreaditem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('article__isnull', False), ('link__isnull', True)), models.Q(('article__isnull', True), ('link__isnull', False)), _connector='OR'), name='personal_thread_item_article_xor_link'),
        ),
        migrations.AddField(
            model_name='communitythreadopinion',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='news.personalcontextthread'),
        ),
        migrations.AddField(
            model_name='communitythreadopinion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_thread_opinions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitythreadreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitythreadreport',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='news.personalcontextthread'),
        ),
        migrations.AddConstraint(
            model_name='communitythreadopinion',
            constraint=models.UniqueConstraint(fields=('user', 'thread'), name='one_opinion_per_user_community_thread'),
        ),
        migrations.AddConstraint(
            model_name='communitythreadopinion',
            constraint=models.CheckConstraint(condition=models.Q(('polarity__in', ['positive', 'negative'])), name='community_opinion_valid_polarity'),
        ),
        migrations.AddConstraint(
            model_name='communitythreadreport',
            constraint=models.UniqueConstraint(fields=('reporter', 'thread'), name='one_report_per_user_thread'),
        ),
    ]
