# Generated by Django 5.1.15 on 2026-09-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0079_community_threads'),
    ]

    operations = [
        migrations.AddField(
            model_name='spindiagnosis',
            name='diagnosed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Kiedy wykonano płatną diagnozę.', null=True),
        ),
        migrations.AddField(
            model_name='spindiagnosis',
            name='screen_score',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Jak bardzo post jest wart sprawdzenia według strażnika (0–100).', null=True),
        ),
        migrations.AlterField(
            model_name='clinicdailymessage',
            name='status',
            field=models.CharField(choices=[('flagged', 'Strażnik: warte sprawdzenia — czeka na decyzję o badaniu'), ('queued', 'W kolejce do płatnej diagnozy'), ('pending_review', 'Czeka na zatwierdzenie'), ('approved', 'Zatwierdzona'), ('rejected', 'Odrzucona'), ('failed', 'Błąd analizy'), ('not_applicable', 'Bez treści do oceny')], db_index=True, default='pending_review', max_length=16),
        ),
        migrations.AlterField(
            model_name='spindiagnosis',
            name='status',
            field=models.CharField(choices=[('flagged', 'Strażnik: warte sprawdzenia — czeka na decyzję o badaniu'), ('queued', 'W kolejce do płatnej diagnozy'), ('pending_review', 'Czeka na zatwierdzenie'), ('approved', 'Zatwierdzona'), ('rejected', 'Odrzucona'), ('failed', 'Błąd analizy'), ('not_applicable', 'Bez treści do oceny')], db_index=True, default='pending_review', max_length=16),
        ),
        migrations.AlterField(
            model_name='spindiagnosis',
            name='triage',
            field=models.JSONField(blank=True, default=dict, help_text='Ocena strażnika: wynik 0–100, uzasadnienie, model.'),
        ),
    ]
