# Generated by Django 5.1.15 on 2026-09-26 18:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0080_clinic_watcher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicdailymessage',
            name='analysis',
            field=models.TextField(blank=True, help_text='Dłuższa analiza przekazu (widok po kliknięciu).'),
        ),
        migrations.CreateModel(
            name='ClinicInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, help_text='Dzień emisji materiału (zwykle poprzedni dzień).')),
                ('url', models.URLField(max_length=300)),
                ('video_id', models.CharField(max_length=11, unique=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('channel', models.CharField(blank=True, max_length=200)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('guest_name', models.CharField(blank=True, max_length=200)),
                ('guest_role', models.CharField(blank=True, max_length=200)),
                ('host_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('flagged', 'Strażnik: warte sprawdzenia — czeka na decyzję o badaniu'), ('queued', 'W kolejce do płatnej diagnozy'), ('pending_review', 'Czeka na zatwierdzenie'), ('approved', 'Zatwierdzona'), ('rejected', 'Odrzucona'), ('failed', 'Błąd analizy'), ('not_applicable', 'Bez treści do oceny')], db_index=True, default='queued', max_length=16)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('overall', models.TextField(blank=True)),
                ('guest_analysis', models.JSONField(blank=True, default=dict)),
                ('host_analysis', models.JSONField(blank=True, default=dict)),
                ('limitations', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('diagnosed_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_reason', models.CharField(blank=True, max_length=240)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wywiad dnia',
                'verbose_name_plural': 'wywiady dnia',
                'ordering': ['-day', '-created_at'],
            },
        ),
    ]
