# Generated by Django 5.1.15 on 2026-09-27 01:56

from django.db import migrations, models


def fill_youtube_urls(apps, schema_editor):
    """Kanały potwierdzone przed dodaniem pola: link YouTube trafia do źródła, które go podlinkowało."""
    Channel = apps.get_model('news', 'OfficialVideoChannel')
    Source = apps.get_model('news', 'Source')
    for row in Channel.objects.filter(status='confirmed', subject_content_type__model='source').exclude(channel_url=''):
        Source.objects.filter(pk=row.subject_object_id).exclude(url__contains='youtube.com').update(youtube_url=row.channel_url)


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0082_spin_x_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='x_handle',
            field=models.CharField(blank=True, help_text='Konto X podlinkowane na stronie głównej źródła (dowód w ImportState source-social).', max_length=15, verbose_name='konto X'),
        ),
        migrations.AddField(
            model_name='source',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Potwierdzony kanał YouTube źródła (OfficialVideoChannel).', max_length=300, verbose_name='kanał YouTube'),
        ),
        migrations.RunPython(fill_youtube_urls, migrations.RunPython.noop),
    ]
