# Generated by Django 5.1.15 on 2026-09-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0083_source_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalpost',
            name='availability_checked_at',
            field=models.DateTimeField(blank=True, help_text='Ostatnie sprawdzenie, czy wpis nadal istnieje na X (darmowy oEmbed).', null=True),
        ),
        migrations.AddField(
            model_name='politicalpost',
            name='unavailable_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Kiedy zauważyliśmy, że wpis usunięto albo stał się niedostępny (treść wtedy usuwamy).', null=True),
        ),
    ]
