# Generated by Django 5.1.15 on 2026-09-27 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0086_post_archive_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('pending', 'czeka na potwierdzenie'), ('confirmed', 'potwierdzony'), ('unsubscribed', 'wypisany')], db_index=True, default='pending', max_length=12)),
                ('token', models.CharField(help_text='Link potwierdzenia i wypisania — bez logowania.', max_length=64, unique=True)),
                ('consent_version', models.CharField(help_text='Wersja treści zgody, którą zaznaczono przy zapisie.', max_length=16)),
                ('source', models.CharField(blank=True, help_text='Miejsce zapisu na stronie (np. home, o-nas).', max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
