# Generated by Django 5.1.15 on 2026-09-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0087_newsletter_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicfigure',
            name='organisations_checked_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Kiedy agent KRS ostatnio szukał podmiotów tej osoby.', null=True),
        ),
        migrations.AddField(
            model_name='publicfigureorganisationrelation',
            name='organ',
            field=models.CharField(blank=True, help_text='Organ z KRS, np. zarząd, rada nadzorcza.', max_length=255),
        ),
        migrations.AddField(
            model_name='publicfigureorganisationrelation',
            name='since',
            field=models.DateField(blank=True, help_text='Data wpisu do KRS (albo ze źródeł).', null=True),
        ),
        migrations.AddField(
            model_name='publicfigureorganisationrelation',
            name='sources',
            field=models.JSONField(blank=True, default=list, help_text='Publiczne źródła relacji: [{url, title}].'),
        ),
        migrations.AddField(
            model_name='publicfigureorganisationrelation',
            name='until',
            field=models.DateField(blank=True, help_text='Data wykreślenia z KRS (albo ze źródeł).', null=True),
        ),
        migrations.AddField(
            model_name='publicfigureorganisationrelation',
            name='verification_method',
            field=models.CharField(choices=[('editor', 'Potwierdzone przez zespół'), ('krs_register', 'Potwierdzone w KRS (organ, funkcja i inicjały zgodne)'), ('public_sources', 'Potwierdzone w co najmniej dwóch niezależnych źródłach')], default='editor', max_length=16),
        ),
        migrations.AddField(
            model_name='registeredorganisation',
            name='legal_form',
            field=models.CharField(blank=True, help_text='Forma prawna z KRS.', max_length=128),
        ),
        migrations.AddField(
            model_name='registeredorganisation',
            name='register',
            field=models.CharField(blank=True, help_text='Rejestr KRS: P — przedsiębiorców, S — stowarzyszeń i fundacji.', max_length=1),
        ),
        migrations.AddField(
            model_name='registeredorganisation',
            name='sector',
            field=models.CharField(choices=[('state', 'Spółka Skarbu Państwa lub państwowa'), ('municipal', 'Spółka komunalna lub samorządowa'), ('public', 'Inny podmiot publiczny'), ('private', 'Podmiot prywatny'), ('ngo', 'Organizacja pozarządowa'), ('unknown', 'Nieustalone')], db_index=True, default='unknown', max_length=12),
        ),
        migrations.AddField(
            model_name='registeredorganisation',
            name='sector_note',
            field=models.TextField(blank=True, help_text='Skąd wiemy, że podmiot jest państwowy lub komunalny.'),
        ),
    ]
