# Generated by Django 5.1.15 on 2026-09-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0088_krs_automatic_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicfigurerole',
            name='party',
            field=models.CharField(blank=True, help_text='Klub albo partia w czasie tej funkcji (np. klub w danej kadencji Sejmu).', max_length=64),
        ),
        migrations.AddField(
            model_name='publicfigurerole',
            name='since',
            field=models.DateField(blank=True, help_text='Początek funkcji z oficjalnego źródła (np. ślubowanie posła).', null=True),
        ),
        migrations.AddField(
            model_name='publicfigurerole',
            name='until',
            field=models.DateField(blank=True, help_text='Koniec funkcji z oficjalnego źródła (np. wygaśnięcie mandatu, koniec kadencji).', null=True),
        ),
    ]
