# Generated by Django 5.1.15 on 2026-09-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0089_role_dates_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='spindiagnosis',
            name='x_posted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Kiedy konto spin.clinic opublikowało wątek diagnozy.', null=True),
        ),
        migrations.AddField(
            model_name='spindiagnosis',
            name='x_posted_ids',
            field=models.JSONField(blank=True, default=list, help_text='Identyfikatory wpisów wątku opublikowanego z konta spin.clinic.'),
        ),
    ]
