# Generated by Django 5.1.15 on 2026-09-29 01:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0091_socialpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilCharterAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=100)),
                ('charter_version', models.CharField(max_length=32)),
                ('charter_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('response', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='spindiagnosis',
            name='lab',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
