# Generated by Django 5.1.15 on 2026-09-30 04:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0095_repairer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=200)),
                ('outcome', models.CharField(max_length=24)),
                ('seconds', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InquisitorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('camp', models.CharField(max_length=12)),
                ('reviewers', models.JSONField(default=list)),
                ('answers', models.JSONField(default=list)),
                ('verdict', models.CharField(default='incomplete', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, max_length=8)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inquisitor_review', to='news.spindiagnosis')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
