# Generated by Django 5.1.15 on 2026-09-30 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0096_council_auditor_inquisitor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('accepted_terms_version', models.CharField(default='', max_length=40)),
                ('accepted_privacy_version', models.CharField(default='', max_length=40)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('google_sub', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('verification_nonce', models.CharField(default='', max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
