# Generated by Django 5.1.15 on 2026-09-30 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('news', '0097_account_identity')]
    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=24)),
                ('target_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'target_id'), name='unique_notification_event')],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_digest', models.CharField(choices=[('off', 'Wyłączony'), ('daily', 'Codziennie'), ('weekly', 'Co tydzień')], default='off', max_length=8)),
                ('push_spin_of_day', models.BooleanField(default=False)),
                ('push_followed', models.BooleanField(default=False)),
                ('push_thread_replies', models.BooleanField(default=False)),
                ('last_digest_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('figure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.publicfigure')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='news.personalcontextthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('figure__isnull', False), ('target_user__isnull', True), ('thread__isnull', True)), models.Q(('figure__isnull', True), ('target_user__isnull', False), ('thread__isnull', True)), models.Q(('figure__isnull', True), ('target_user__isnull', True), ('thread__isnull', False)), _connector='OR'), name='follow_exactly_one_target'), models.UniqueConstraint(fields=('user', 'figure'), name='unique_follow_figure'), models.UniqueConstraint(fields=('user', 'target_user'), name='unique_follow_target_user'), models.UniqueConstraint(fields=('user', 'thread'), name='unique_follow_thread')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=240)),
                ('url', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='notification_user_read')],
            },
        ),
    ]
