# Generated by Django 5.1.15 on 2026-10-01 01:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0099_push_subscriptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(choices=[('strateg', 'strateg'), ('pielgrzym', 'pielgrzym')], max_length=12)),
                ('kind', models.CharField(choices=[('signal', 'signal'), ('idea', 'idea'), ('finding', 'finding'), ('experiment', 'experiment'), ('request', 'request'), ('report', 'report')], max_length=12)),
                ('track', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('', '—')], max_length=1)),
                ('title', models.CharField(max_length=240)),
                ('body', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('critiques', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'new'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('done', 'done'), ('pending', 'pending'), ('approved', 'approved'), ('denied', 'denied')], default='new', max_length=12)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['agent', 'kind', 'created_at'], name='agent_kind_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('score__lte', 100)), name='agent_score_range')],
            },
        ),
    ]
