# Generated by Django 5.1.15 on 2026-10-01 10:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_comments(apps, schema_editor):
    import hashlib
    import unicodedata
    Opinion = apps.get_model('news', 'SpinOpinion')
    Comment = apps.get_model('news', 'ClinicComment')
    db = schema_editor.connection.alias
    for row in Opinion.objects.using(db).exclude(body='').iterator(chunk_size=500):
        digest = hashlib.sha256(' '.join(unicodedata.normalize('NFKC', row.body).casefold().split()).encode('utf-8')).hexdigest()
        Comment.objects.using(db).get_or_create(legacy_opinion_id=row.pk, defaults={
            'author_id': row.user_id, 'diagnosis_id': row.diagnosis_id, 'body': row.body,
            'body_hash': digest, 'created_at': row.created_at, 'screening': 'legacy', 'needs_review': True,
        })


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0100_agents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('body_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_reason', models.CharField(blank=True, max_length=240)),
                ('screening', models.CharField(choices=[('pending', 'Sprawdzanie'), ('clean', 'Bez naruszeń'), ('flagged', 'Ukryte przez filtr'), ('unavailable', 'Brak odpowiedzi filtra'), ('legacy', 'Komentarz sprzed migracji')], db_index=True, default='pending', max_length=16)),
                ('needs_review', models.BooleanField(db_index=True, default=True)),
                ('reply_notified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClinicCommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Naruszenie zasad'), ('privacy', 'Dane prywatne'), ('off_topic', 'Poza tematem'), ('other', 'Inne')], max_length=16)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarity', models.CharField(choices=[('positive', 'Trafna diagnoza'), ('negative', 'Nietrafna diagnoza')], max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='spinopinion',
            name='spin_opinion_valid_polarity',
        ),
        migrations.AddField(
            model_name='accountidentity',
            name='comments_blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spinopinion',
            name='polarity',
            field=models.CharField(blank=True, choices=[('positive', 'Trafna diagnoza'), ('negative', 'Nietrafna diagnoza')], max_length=8, null=True),
        ),
        migrations.AddConstraint(
            model_name='spinopinion',
            constraint=models.CheckConstraint(condition=models.Q(('polarity__isnull', True), ('polarity__in', ['positive', 'negative']), _connector='OR'), name='spin_opinion_valid_polarity'),
        ),
        migrations.AddField(
            model_name='cliniccomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliniccomment',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.spindiagnosis'),
        ),
        migrations.AddField(
            model_name='cliniccomment',
            name='hidden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliniccomment',
            name='interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.clinicinterview'),
        ),
        migrations.AddField(
            model_name='cliniccomment',
            name='legacy_opinion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_comment', to='news.spinopinion'),
        ),
        migrations.AddField(
            model_name='cliniccomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='news.cliniccomment'),
        ),
        migrations.AddField(
            model_name='cliniccommentreport',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='news.cliniccomment'),
        ),
        migrations.AddField(
            model_name='cliniccommentreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_comment_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliniccommentreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewopinion',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='news.clinicinterview'),
        ),
        migrations.AddField(
            model_name='interviewopinion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_opinions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cliniccomment',
            index=models.Index(fields=['author', 'created_at'], name='clinic_comment_author_date'),
        ),
        migrations.AddConstraint(
            model_name='cliniccomment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('diagnosis__isnull', False), ('interview__isnull', True)), models.Q(('diagnosis__isnull', True), ('interview__isnull', False)), _connector='OR'), name='clinic_comment_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='cliniccommentreport',
            constraint=models.UniqueConstraint(fields=('reporter', 'comment'), name='one_report_per_user_clinic_comment'),
        ),
        migrations.AddConstraint(
            model_name='interviewopinion',
            constraint=models.UniqueConstraint(fields=('user', 'interview'), name='one_opinion_per_user_interview'),
        ),
        migrations.AddConstraint(
            model_name='interviewopinion',
            constraint=models.CheckConstraint(condition=models.Q(('polarity__in', ['positive', 'negative'])), name='interview_opinion_valid_polarity'),
        ),
        migrations.RunPython(migrate_comments, migrations.RunPython.noop),
    ]
