# Generated by Django 5.1.15 on 2026-10-01 21:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0102_account_warden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spindiagnosis',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='spindiagnosis',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spindiagnosis',
            name='withdrawn_reason',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='spindiagnosis',
            name='status',
            field=models.CharField(choices=[('flagged', 'Strażnik: warte sprawdzenia — czeka na decyzję o badaniu'), ('queued', 'W kolejce do płatnej diagnozy'), ('pending_review', 'Czeka na zatwierdzenie'), ('approved', 'Zatwierdzona'), ('rejected', 'Odrzucona'), ('failed', 'Błąd analizy'), ('not_applicable', 'Bez treści do oceny'), ('withdrawn', 'Wycofana')], db_index=True, default='pending_review', max_length=16),
        ),
        migrations.CreateModel(
            name='ClinicAuthorReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1500, validators=[django.core.validators.MaxLengthValidator(1500)], verbose_name='treść')),
                ('source_url', models.URLField(max_length=500, verbose_name='link do źródła')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data otrzymania')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='data publikacji')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_replies', to='news.spindiagnosis')),
            ],
            options={
                'verbose_name': 'odpowiedź autora',
                'verbose_name_plural': 'odpowiedzi autorów',
                'ordering': ['-published_at', '-pk'],
            },
        ),
    ]
