# Generated by Django 5.1.15 on 2026-10-02 03:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0103_clinic_corrections'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=180, unique=True)),
                ('rule', models.CharField(db_index=True, max_length=48)),
                ('severity', models.CharField(choices=[('critical', 'Krytyczny'), ('warning', 'Uwaga')], max_length=12)),
                ('title', models.CharField(max_length=240)),
                ('details', models.JSONField(default=dict)),
                ('repairer', models.CharField(blank=True, max_length=160)),
                ('instruction', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('open', 'Otwarty'), ('closed', 'Zamknięty')], db_index=True, default='open', max_length=8)),
                ('since', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('occurrences', models.PositiveIntegerField(default=0)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_dispatch_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_note', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['first_seen', 'pk'],
            },
        ),
    ]
