# Generated by Django 5.1.15 on 2026-10-02 03:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0104_duty_alarm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalaccount',
            name='disabled_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='politicalaccount',
            name='name_history',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.CreateModel(
            name='WardenReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('category', models.CharField(max_length=24)),
                ('first_decision', models.CharField(default='disable', max_length=12)),
                ('fingerprint', models.CharField(max_length=64)),
                ('evidence', models.JSONField(default=dict)),
                ('second_evidence', models.JSONField(blank=True, default=dict)),
                ('second_decision', models.CharField(blank=True, max_length=12)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('owner', 'owner'), ('disabled', 'disabled'), ('kept', 'kept'), ('superseded', 'superseded')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.CharField(blank=True, max_length=32)),
                ('last_error', models.CharField(blank=True, max_length=240)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warden_reviews', to='news.politicalaccount')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SebaReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, default='queued', max_length=16)),
                ('phase', models.CharField(default='critique', max_length=12)),
                ('rounds', models.PositiveSmallIntegerField(default=0)),
                ('revision', models.JSONField(blank=True, default=dict)),
                ('critiques', models.JSONField(blank=True, default=list)),
                ('due_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.CharField(blank=True, max_length=32)),
                ('last_error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seba_review', to='news.agentnote')),
                ('warden', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seba_review', to='news.wardenreview')),
            ],
        ),
        migrations.AddConstraint(
            model_name='wardenreview',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'owner'])), fields=('account',), name='warden_one_open_review'),
        ),
        migrations.AddConstraint(
            model_name='sebareview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('note__isnull', False), ('warden__isnull', True)), models.Q(('note__isnull', True), ('warden__isnull', False)), _connector='OR'), name='seba_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='sebareview',
            constraint=models.CheckConstraint(condition=models.Q(('rounds__lte', 2)), name='seba_two_rounds'),
        ),
    ]
