# Generated by Django 5.1.15 on 2026-10-02 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_social(apps, schema_editor):
    db = schema_editor.connection.alias
    apps.get_model('auth', 'Group').objects.using(db).get_or_create(name='social')
    Material = apps.get_model('news', 'SocialMaterial')
    ids = apps.get_model('news', 'SocialPost').objects.using(db).filter(platform='manual').values_list('diagnosis_id', flat=True)
    for diagnosis_id in ids.iterator():
        # Even historical deletion alerts still need a human confirmation.
        Material.objects.using(db).get_or_create(diagnosis_id=diagnosis_id)


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0107_spindiagnosis_plain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAssistantUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('calls', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('shorts', 'YouTube Shorts'), ('facebook', 'Facebook (film)'), ('instagram', 'Instagram (Reels)'), ('bluesky', 'Bluesky'), ('manual', 'TikTok i YouTube Shorts (mail z filmem)')], max_length=12),
        ),
        migrations.CreateModel(
            name='SocialMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_material', to='news.spindiagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='SocialTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=4000)),
                ('kind', models.CharField(choices=[('question', 'Pytanie'), ('task', 'Zadanie')], max_length=12)),
                ('status', models.CharField(choices=[('new', 'Nowe'), ('progress', 'W toku'), ('done', 'Zrobione')], default='new', max_length=12)),
                ('answer', models.TextField(blank=True, max_length=8000)),
                ('answered_by', models.CharField(blank=True, choices=[('assistant', 'Asystent'), ('owner', 'Właściciel'), ('claude', 'Claude')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.RunPython(seed_social, migrations.RunPython.noop),
    ]
