# Generated by Django 5.1.15 on 2026-10-03 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0109_personal_thread_item_link_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('refreshed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='clinicinterview',
            name='selection_method',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='clinicinterview',
            name='selection_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InterviewCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=11)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('channel', models.CharField(blank=True, max_length=200)),
                ('guest_name', models.CharField(blank=True, max_length=300)),
                ('guest_keys', models.JSONField(default=list)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('score', models.PositiveBigIntegerField(default=0)),
                ('loudness', models.PositiveBigIntegerField(default=0)),
                ('top', models.BooleanField(default=False)),
                ('from_ranking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='news.interviewballot')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='news.interviewcandidate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='news.interviewballot')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='news.interviewcandidate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='interviewcandidate',
            constraint=models.UniqueConstraint(fields=('ballot', 'video_id'), name='interview_candidate_video_day'),
        ),
        migrations.AddConstraint(
            model_name='interviewsubmission',
            constraint=models.UniqueConstraint(fields=('user', 'candidate'), name='interview_submission_once'),
        ),
        migrations.AddConstraint(
            model_name='interviewvote',
            constraint=models.UniqueConstraint(fields=('user', 'ballot'), name='interview_vote_user_day'),
        ),
    ]
