# Generated by Django 5.1.15 on 2026-10-03 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0111_daily_message_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communitythreadopinion',
            name='comment_added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveConstraint(
            model_name='personalcontextthreaditem',
            name='personal_thread_item_article_xor_link',
        ),
        migrations.AddField(
            model_name='personalcontextthread',
            name='diagnosis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='context_thread', to='news.spindiagnosis'),
        ),
        migrations.AddField(
            model_name='personalcontextthreaditem',
            name='box_data',
            field=models.JSONField(blank=True, help_text='Deterministyczny fragment diagnozy Dr. Spina.', null=True),
        ),
        migrations.AlterField(
            model_name='personalcontextthread',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_context_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='personalcontextthread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('diagnosis__isnull', True), ('owner__isnull', False)), models.Q(('diagnosis__isnull', False), ('owner__isnull', True)), _connector='OR'), name='context_thread_owner_or_diagnosis'),
        ),
        migrations.AddConstraint(
            model_name='personalcontextthreaditem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('article__isnull', False), ('box_data__isnull', True), ('link__isnull', True)), models.Q(('article__isnull', True), ('box_data__isnull', True), ('link__isnull', False)), models.Q(('article__isnull', True), ('box_data__isnull', False), ('link__isnull', True)), _connector='OR'), name='personal_thread_item_article_xor_link'),
        ),
    ]
