# Generated by Django 5.1.15 on 2026-10-03 02:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.models.functions import Coalesce


def preserve_legacy(apps, schema_editor):
    Comment = apps.get_model('news', 'ThreadComment')
    Opinion = apps.get_model('news', 'CommunityThreadOpinion')
    Report = apps.get_model('news', 'ThreadModerationReport')
    LegacyReport = apps.get_model('news', 'CommunityThreadReport')
    alias = schema_editor.connection.alias
    for row in Opinion.objects.using(alias).exclude(body='').annotate(legacy_date=Coalesce('comment_added_at', 'created_at')).order_by('legacy_date', 'pk').iterator():
        Comment.objects.using(alias).create(thread_id=row.thread_id, author_id=row.user_id,
            body=row.body, created_at=row.comment_added_at or row.created_at)
    for row in LegacyReport.objects.using(alias).all().iterator():
        Report.objects.using(alias).create(thread_id=row.thread_id, reporter_id=row.reporter_id,
            reason=row.reason, details=row.details, created_at=row.created_at,
            target_author_id=row.thread.owner_id, target_kind='thread',
            status='new' if row.status == 'new' else 'legacy_resolved', snapshot='',
            ai_assessment={'state': 'legacy'})


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0112_diagnosis_threads_084'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('hidden_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ThreadModerationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('hide', 'Ukryj'), ('restore', 'Przywróć')], max_length=8)),
                ('rule', models.CharField(max_length=40)),
                ('explanation', models.TextField()),
                ('is_appeal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadModerationMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(null=True)),
                ('last_attempt_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadModerationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=16)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(db_index=True, default='new', max_length=16)),
                ('ai_assessment', models.JSONField(default=dict)),
                ('snapshot', models.TextField()),
                ('target_kind', models.CharField(default='thread', max_length=8)),
                ('appeal', models.TextField(blank=True)),
                ('appealed_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ThreadRateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='communitythreadopinion',
            name='community_opinion_valid_polarity',
        ),
        migrations.AlterField(
            model_name='communitythreadopinion',
            name='polarity',
            field=models.CharField(choices=[('positive', 'Zgadzam się'), ('doubt', 'Mam wątpliwości'), ('negative', 'Nie zgadzam się')], max_length=8),
        ),
        migrations.AlterField(
            model_name='personalcontextthread',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personalcontextthreaditem',
            name='link_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='personalcontextthreaditem',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='communitythreadopinion',
            constraint=models.CheckConstraint(condition=models.Q(('polarity__in', ['positive', 'doubt', 'negative'])), name='community_opinion_valid_polarity'),
        ),
        migrations.AddField(
            model_name='threadcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threadcomment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.personalcontextthread'),
        ),
        migrations.AddField(
            model_name='threadmoderationdecision',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threadmoderationmail',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail', to='news.threadmoderationdecision'),
        ),
        migrations.AddField(
            model_name='threadmoderationreport',
            name='appealed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threadmoderationreport',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.threadcomment'),
        ),
        migrations.AddField(
            model_name='threadmoderationreport',
            name='target_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threadmoderationreport',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threadmoderationreport',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_reports', to='news.personalcontextthread'),
        ),
        migrations.AddField(
            model_name='threadmoderationdecision',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='news.threadmoderationreport'),
        ),
        migrations.AddField(
            model_name='threadrateevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='threadmoderationmail',
            constraint=models.UniqueConstraint(fields=('decision', 'recipient'), name='thread_decision_recipient_085'),
        ),
        migrations.AddIndex(
            model_name='threadrateevent',
            index=models.Index(fields=['user', 'kind', 'created_at'], name='thread_rate_window_085'),
        ),
        migrations.RunPython(preserve_legacy, migrations.RunPython.noop),
    ]
