# Generated by Django 5.1.15 on 2026-10-03 03:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0113_thread_social_085'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadCommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='personalcontextthread',
            name='context_thread_owner_or_diagnosis',
        ),
        migrations.AddField(
            model_name='communitylink',
            name='x_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='communitylink',
            name='x_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='group_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='personalcontextthread',
            name='continues',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continuations', to='news.personalcontextthread'),
        ),
        migrations.AddField(
            model_name='personalcontextthread',
            name='narrative_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='narrative_thread', to='news.clinicdailymessage'),
        ),
        migrations.AddField(
            model_name='personalcontextthread',
            name='narrative_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userxconnection',
            name='use_x_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountidentity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='personalcontextthread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('diagnosis__isnull', True), ('narrative_message__isnull', True), ('owner__isnull', False)), models.Q(('diagnosis__isnull', False), ('narrative_message__isnull', True), ('owner__isnull', True)), models.Q(('diagnosis__isnull', True), ('narrative_message__isnull', False), ('owner__isnull', True)), _connector='OR'), name='context_thread_origin_087'),
        ),
        migrations.AddField(
            model_name='threadcommentreaction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='news.threadcomment'),
        ),
        migrations.AddField(
            model_name='threadcommentreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='threadcommentreaction',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='comment_reaction_user_087'),
        ),
    ]
