# Generated by Django 5.1.15 on 2026-10-03 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0115_account_dashboard_086'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='follow',
            name='mode',
            field=models.CharField(choices=[('posts', 'Każdy wpis'), ('diagnoses', 'Diagnozy'), ('strong_spin', 'Tylko silny spin')], default='diagnoses', max_length=16),
        ),
        migrations.AddField(
            model_name='notification',
            name='figure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.publicfigure'),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_pending',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'figure', 'kind', '-created_at'], name='notification_figure_088'),
        ),
        migrations.AddField(
            model_name='politicalaccount',
            name='include_replies',
            field=models.BooleanField(default=True, verbose_name='Czytaj odpowiedzi'),
        ),
        migrations.AddField(
            model_name='politicalaccount',
            name='include_reposts',
            field=models.BooleanField(default=False, verbose_name='Czytaj podania dalej'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('mode', 'diagnoses'), models.Q(('figure__isnull', False), ('mode__in', ['posts', 'strong_spin'])), _connector='OR'), name='follow_figure_mode_088'),
        ),
        migrations.AddField(
            model_name='notificationpost',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='news.notification'),
        ),
        migrations.AddField(
            model_name='notificationpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.politicalpost'),
        ),
        migrations.AddConstraint(
            model_name='notificationpost',
            constraint=models.UniqueConstraint(fields=('notification', 'post'), name='unique_notification_post_088'),
        ),
    ]
