# Generated by Django 5.1.15 on 2026-10-03 12:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_states(apps, schema_editor):
    State = apps.get_model('news', 'PublicCollectionState')
    for source in ('votes', 'statements', 'interpellations', 'questions', 'lobby_mswia',
                   'lobby_sejm', 'consultations', 'pkw', 'assets', 'meta_ads'):
        State.objects.using(schema_editor.connection.alias).get_or_create(source=source)


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0117_x_watch_batched_089'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCollectionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32, unique=True)),
                ('since', models.DateField(blank=True, null=True)),
                ('cycle_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_complete_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='idle', max_length=32)),
                ('record_count', models.PositiveBigIntegerField(default=0)),
                ('budget_day', models.DateField(blank=True, null=True)),
                ('requests_today', models.PositiveIntegerField(default=0)),
                ('next_request_at', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.CharField(blank=True, max_length=36)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=32)),
                ('kind', models.CharField(db_index=True, max_length=32)),
                ('external_id', models.CharField(max_length=256)),
                ('source_url', models.URLField(max_length=2048)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_sha256', models.CharField(max_length=64)),
                ('response_url', models.URLField(max_length=2048)),
                ('term', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('title', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('data', models.JSONField(default=dict)),
                ('print_number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('fetch_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.fetchattempt')),
                ('official_print', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.officialrecord')),
            ],
            options={
                'ordering': ['-fetched_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PublicRecordPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.PositiveSmallIntegerField()),
                ('mp_id', models.PositiveIntegerField()),
                ('figure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_public_records', to='news.publicfigure')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='news.publicrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PublicCollectionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=64)),
                ('url', models.URLField(max_length=2048)),
                ('kind', models.CharField(max_length=32)),
                ('context', models.JSONField(default=dict)),
                ('done', models.BooleanField(default=False)),
                ('last_error', models.CharField(blank=True, max_length=120)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('retry_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='news.publiccollectionstate')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'done', 'id'], name='public_job_pending_090')],
                'constraints': [models.UniqueConstraint(fields=('state', 'identity'), name='public_collection_job_090')],
            },
        ),
        migrations.AddConstraint(
            model_name='publicrecord',
            constraint=models.UniqueConstraint(fields=('source', 'kind', 'external_id'), name='public_record_identity_090'),
        ),
        migrations.AddConstraint(
            model_name='publicrecordperson',
            constraint=models.UniqueConstraint(fields=('record', 'term', 'mp_id'), name='public_record_person_090'),
        ),
        migrations.RunPython(seed_states, migrations.RunPython.noop),
    ]
