# Generated by Django 5.1.15 on 2026-10-03 12:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0118_public_records_090'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDailyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('calls', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weekly', 'Raport tygodniowy przekazu'), ('topic', 'Monitoring tematu / branży'), ('profile', 'Profil wypowiedzi'), ('weekly_en', 'Weekly in English'), ('research', 'Dane do badań')], max_length=16, verbose_name='typ')),
                ('audience', models.CharField(max_length=64, verbose_name='odbiorcy')),
                ('sample_key', models.CharField(max_length=64, unique=True)),
                ('scope', models.JSONField(default=dict, verbose_name='zakres')),
                ('status', models.CharField(choices=[('queued', 'W kolejce'), ('working', 'W recenzji'), ('blocked', 'Brakuje danych'), ('awaiting_approval', 'Do zatwierdzenia'), ('approved', 'Zatwierdzony'), ('rejected', 'Odrzucony')], db_index=True, default='queued', max_length=24, verbose_name='status')),
                ('snapshot', models.JSONField(default=dict, verbose_name='dane i metoda')),
                ('gate', models.JSONField(default=dict, verbose_name='gotowość danych')),
                ('draft', models.JSONField(default=dict, verbose_name='tekst')),
                ('extra_roles', models.JSONField(default=list, verbose_name='konsultacje')),
                ('panel', models.JSONField(default=dict, verbose_name='modele')),
                ('phase', models.CharField(default='draft', max_length=24)),
                ('round', models.PositiveSmallIntegerField(default=1, verbose_name='runda')),
                ('cursor', models.PositiveSmallIntegerField(default=0)),
                ('objections', models.JSONField(default=list, verbose_name='zastrzeżenia')),
                ('pdf', models.BinaryField(null=True)),
                ('csv', models.BinaryField(null=True)),
                ('method', models.TextField(blank=True, verbose_name='metoda i źródła')),
                ('artifact_hash', models.CharField(blank=True, max_length=64)),
                ('approved_hash', models.CharField(blank=True, max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzono')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'raport dla instytucji',
                'verbose_name_plural': 'raporty dla instytucji',
            },
        ),
        migrations.CreateModel(
            name='ReportReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField()),
                ('slot', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=200)),
                ('draft_hash', models.CharField(max_length=64)),
                ('decision', models.CharField(default='started', max_length=24)),
                ('response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='news.institutionalreport')),
            ],
            options={
                'verbose_name': 'recenzja raportu',
                'verbose_name_plural': 'recenzje raportów',
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(fields=('report', 'slot'), name='reports_unique_step_092')],
            },
        ),
        migrations.AddConstraint(
            model_name='institutionalreport',
            constraint=models.CheckConstraint(condition=models.Q(('round__gte', 1), ('round__lte', 3)), name='reports_max_three_rounds_092'),
        ),
    ]
