# Generated by Django 5.1.15 on 2026-10-03 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0119_institutional_reports_092'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.CharField(max_length=200, unique=True, verbose_name='klucz źródłowy')),
                ('kind', models.CharField(choices=[('bill', 'Projekt ustawy'), ('amendment', 'Poprawka'), ('lobbying', 'Sygnał lobbingu'), ('stance', 'Stanowisko w wypowiedzi')], max_length=16, verbose_name='rodzaj')),
                ('topic', models.SlugField(max_length=100, verbose_name='temat')),
                ('day', models.DateField(db_index=True, verbose_name='data')),
                ('analysis', models.CharField(help_text='Własny opis analityczny. Bez treści i cytatów z cudzych wpisów.', max_length=500, verbose_name='nasza analiza')),
                ('source_url', models.URLField(max_length=1024, verbose_name='źródło')),
                ('corroborating_url', models.URLField(blank=True, max_length=1024, verbose_name='drugie źródło')),
                ('confidence', models.CharField(choices=[('low', 'Niska'), ('medium', 'Umiarkowana'), ('high', 'Wysoka')], default='low', max_length=12, verbose_name='pewność')),
                ('confidence_reason', models.CharField(max_length=400, verbose_name='podstawa poziomu pewności')),
                ('stance', models.CharField(blank=True, choices=[('support', 'Poparcie'), ('oppose', 'Sprzeciw'), ('neutral', 'Neutralne')], max_length=12, verbose_name='stanowisko')),
                ('supporting_vote', models.CharField(blank=True, help_text='Dokładna wartość vote ze źródła. Nie wnioskuj jej z tytułu głosowania.', max_length=30, verbose_name='głos oznaczający poparcie tej tezy')),
                ('approved', models.BooleanField(default=False, verbose_name='zweryfikowane')),
                ('verified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ballot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.ballot', verbose_name='powiązany głos')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.spindiagnosis', verbose_name='diagnoza wypowiedzi')),
                ('figure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.publicfigure', verbose_name='osoba')),
                ('verified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'obserwacja do raportów',
                'verbose_name_plural': 'obserwacje do raportów',
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'stance')), fields=('topic', 'diagnosis'), name='reports_one_stance_per_topic_092')],
            },
        ),
    ]
