# Generated by Django 5.1.15 on 2026-10-03 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def hold_existing(apps, schema_editor):
    # Old publications have no two-pass review. The worker queues them from local data.
    apps.get_model('news', 'PersonalContextThread').objects.using(schema_editor.connection.alias).filter(
        owner__isnull=True).update(is_public=False)
    apps.get_model('news', 'Thread').objects.using(schema_editor.connection.alias).filter(
        slug__startswith='dr-spin-').update(published=False)


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0120_report_observations_092'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Do kontroli'), ('waiting', 'Czeka na darmowy model'), ('rejected', 'Odrzucona'), ('approved', 'Zatwierdzona')], db_index=True, default='pending', max_length=12)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('fingerprint', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('working_texts', models.JSONField(default=dict)),
                ('step', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadReviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('role', models.CharField(max_length=40)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('result', models.CharField(choices=[('pass', 'Zaliczono'), ('reject', 'Odrzucono'), ('wait', 'Oczekiwanie')], max_length=12)),
                ('reason', models.TextField()),
                ('texts', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='personalcontextthread',
            name='context_thread_origin_087',
        ),
        migrations.AddField(
            model_name='personalcontextthread',
            name='signal_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='personalcontextthread',
            name='signal_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='personalcontextthread',
            name='signal_kind',
            field=models.CharField(blank=True, choices=[('', 'Pozostałe'), ('lobbying', 'Sygnał lobbingu'), ('new_narrative', 'Nowa narracja')], default='', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='personalcontextthread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('diagnosis__isnull', True), ('narrative_message__isnull', True), ('owner__isnull', False), ('signal_kind', '')), models.Q(('diagnosis__isnull', False), ('narrative_message__isnull', True), ('owner__isnull', True), ('signal_kind', '')), models.Q(('diagnosis__isnull', True), ('narrative_message__isnull', False), ('owner__isnull', True), ('signal_kind', '')), models.Q(('diagnosis__isnull', True), ('narrative_message__isnull', True), ('owner__isnull', True), ('signal_key__isnull', False), ('signal_kind__in', ['lobbying', 'new_narrative'])), _connector='OR'), name='context_thread_origin_091'),
        ),
        migrations.AddField(
            model_name='threadreview',
            name='editorial_thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_review', to='news.thread'),
        ),
        migrations.AddField(
            model_name='threadreview',
            name='thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_review', to='news.personalcontextthread'),
        ),
        migrations.AddField(
            model_name='threadreviewround',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='news.threadreview'),
        ),
        migrations.AddConstraint(
            model_name='threadreview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('editorial_thread__isnull', True), ('thread__isnull', False)), models.Q(('editorial_thread__isnull', False), ('thread__isnull', True)), _connector='OR'), name='thread_review_target_091'),
        ),
        migrations.RunPython(hold_existing, migrations.RunPython.noop),
    ]
