# Generated by Django 5.1.15 on 2026-10-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0121_thread_signals_review_091'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadcommentreaction',
            name='polarity',
            field=models.CharField(choices=[('positive', 'Trafny'), ('doubt', 'Wątpliwy'), ('negative', 'Nietrafny')], default='positive', max_length=8),
        ),
    ]
