# Generated by Django 5.1.15 on 2026-10-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0122_comment_reaction_polarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcontextthread',
            name='admitted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
