# Generated by Django 5.1.15 on 2026-10-03 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0123_thread_admission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadStepReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('box', 'Boks'), ('context', 'Powiązanie')], max_length=8)),
                ('polarity', models.CharField(choices=[('positive', 'Trafny'), ('doubt', 'Wątpliwy'), ('negative', 'Nietrafny')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_reactions', to='news.personalcontextthreaditem')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_reactions', to='news.personalcontextthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_step_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['thread', 'user'], name='news_thread_thread__805021_idx')],
                'constraints': [models.UniqueConstraint(fields=('item', 'part', 'user'), name='thread_step_reaction_user')],
            },
        ),
    ]
