# Generated by Django 5.1.15 on 2026-10-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0124_thread_step_reaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitythreadreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'zgłoszenie spinki', 'verbose_name_plural': 'zgłoszenia spinek'},
        ),
        migrations.AlterField(
            model_name='thread',
            name='editorial_slot',
            field=models.CharField(blank=True, choices=[('', 'Pozostałe spinki'), ('government', 'Przekaz dnia obozu rządzącego'), ('opposition', 'Przekaz dnia opozycji')], default='', max_length=16),
        ),
    ]
