# Generated by Django 5.1.15 on 2026-10-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0125_spinki_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepreference',
            name='nick_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
