# Generated by Django 5.1.15 on 2026-10-03 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0126_nick_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcontextthread',
            name='repin_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repins', to='news.personalcontextthread'),
        ),
    ]
