# Generated by Django 5.1.15 on 2026-10-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0127_repin_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcontextthreaditem',
            name='link_kind',
            field=models.CharField(blank=True, choices=[('', '-'), ('bo', 'bo'), ('ale', 'ale'), ('czy_na_pewno', 'czy na pewno?'), ('przeczy', 'przeczy'), ('wynika_z', 'wynika z')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='personalcontextthreaditem',
            name='role',
            field=models.CharField(blank=True, choices=[('', '-'), ('teza', 'Teza'), ('fakt', 'Fakt'), ('kontekst', 'Kontekst'), ('pytanie', 'Pytanie'), ('opinia', 'Opinia'), ('wniosek', 'Wniosek')], default='', max_length=12),
        ),
    ]
