# Generated by Django 5.1.15 on 2026-10-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0129_interview_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentnote',
            name='agent',
            field=models.CharField(choices=[('strateg', 'strateg'), ('pielgrzym', 'pielgrzym'), ('ekspert', 'ekspert')], max_length=12),
        ),
    ]
