# Generated by Django 5.1.15 on 2026-10-04 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0130_agent_ekspert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('bug', 'Błąd'), ('idea', 'Pomysł')], default='bug', max_length=8)),
                ('text', models.TextField(max_length=1000)),
                ('path', models.CharField(max_length=200)),
                ('viewport', models.CharField(blank=True, max_length=20)),
                ('theme', models.CharField(blank=True, max_length=10)),
                ('trail', models.JSONField(blank=True, default=list)),
                ('contact', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('new', 'Nowe'), ('fixed', 'Naprawione'), ('rejected', 'Nie dotyczy')], db_index=True, default='new', max_length=10)),
                ('staff_note', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'zgłoszenie błędu',
                'verbose_name_plural': 'zgłoszenia błędów',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JourneyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(db_index=True)),
                ('source', models.CharField(max_length=120)),
                ('target', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=60)),
                ('device', models.CharField(max_length=8)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'krok ścieżki',
                'verbose_name_plural': 'ścieżki użytkowników (zbiorczo)',
                'constraints': [models.UniqueConstraint(fields=('hour', 'source', 'target', 'action', 'device'), name='journey_step_unique')],
            },
        ),
    ]
