# Generated by Django 5.1.15 on 2026-10-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0131_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='text',
            field=models.TextField(max_length=1200),
        ),
    ]
