# Generated by Django 5.1.15 on 2026-10-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0132_bug_text_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcontextthreaditem',
            name='link_kind',
            field=models.CharField(blank=True, choices=[('', '-'), ('bo', 'bo'), ('ale', 'ale'), ('czy_na_pewno', 'czy na pewno?'), ('przeczy', 'przeczy'), ('wynika_z', 'wynika z'), ('jak', 'jak?')], default='', max_length=16),
        ),
    ]
