# Generated by Django 5.1.15 on 2026-10-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0133_link_kind_jak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentnote',
            name='agent',
            field=models.CharField(choices=[('strateg', 'strateg'), ('pielgrzym', 'pielgrzym'), ('ekspert', 'ekspert'), ('recenzent', 'recenzent'), ('projektant', 'projektant')], max_length=12),
        ),
        migrations.AlterField(
            model_name='agentnote',
            name='kind',
            field=models.CharField(choices=[('signal', 'signal'), ('idea', 'idea'), ('finding', 'finding'), ('experiment', 'experiment'), ('request', 'request'), ('report', 'report'), ('review', 'review'), ('audit', 'audit')], max_length=12),
        ),
    ]
