# Generated by Django 5.1.15 on 2026-10-05 22:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0142_przeszlosc_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('rank', models.FloatField(default=0)),
                ('brief', models.TextField(blank=True)),
                ('acceptance', models.JSONField(blank=True, default=list)),
                ('effort', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], default='M', max_length=1)),
                ('executor', models.CharField(choices=[('claude', 'claude'), ('codex', 'codex')], default='claude', max_length=6)),
                ('status', models.CharField(choices=[('proposed', 'proposed'), ('approved', 'approved'), ('in_progress', 'in_progress'), ('done', 'done'), ('dropped', 'dropped')], db_index=True, default='proposed', max_length=12)),
                ('commit', models.CharField(blank=True, max_length=64)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_tickets', to='news.agentnote')),
            ],
            options={
                'verbose_name': 'bilet sprintu',
                'verbose_name_plural': 'Sprint tygodnia: bilety budowy',
                'ordering': ['-rank', '-pk'],
            },
        ),
    ]
