# Generated by Django 5.1.15 on 2026-10-05 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0143_sprint_buildticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingDeviationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.PositiveSmallIntegerField()),
                ('period', models.CharField(choices=[('term', 'Cała kadencja'), ('90d', 'Ostatnie 90 dni')], max_length=10)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'odstępstwa od klubu (wynik)',
                'verbose_name_plural': 'odstępstwa od klubu (wyniki)',
                'constraints': [models.UniqueConstraint(fields=('term', 'period'), name='unique_voting_deviation_snapshot')],
            },
        ),
    ]
