# Generated by Django 5.1.15 on 2026-10-05 22:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0144_voting_deviations'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatedCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField(help_text='Przykładowe brzmienie (najwcześniejszy dostępny wpis klastra).')),
                ('first_at', models.DateTimeField(db_index=True)),
                ('last_at', models.DateTimeField(db_index=True)),
                ('accounts_count', models.PositiveSmallIntegerField(default=0)),
                ('posts_count', models.PositiveSmallIntegerField(default=0)),
                ('accounts', models.JSONField(default=list, help_text='Konta: handle, nazwa, partia, obóz.')),
                ('parties', models.JSONField(default=list)),
                ('camps', models.JSONField(default=list)),
                ('cross_party', models.BooleanField(db_index=True, default=False)),
                ('cross_camp', models.BooleanField(default=False)),
                ('similarity', models.FloatField(default=0, help_text='Najniższe podobieństwo krawędzi w klastrze (Jaccard 5-gramów).')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posts', models.ManyToManyField(related_name='coordinated_clusters', to='news.politicalpost')),
            ],
            options={
                'verbose_name': 'wspólny przekaz (klaster)',
                'verbose_name_plural': 'wspólny przekaz (klastry)',
                'ordering': ['-first_at', '-pk'],
            },
        ),
    ]
