# Generated by Django 5.1.15 on 2026-10-05 22:30

from django.db import migrations, models
from django.utils import timezone


def start_clock(apps, schema_editor):
    # Raporty, które już czekają na zgodę: licznik od wdrożenia (dokładnej chwili przejścia nie zapisywaliśmy).
    apps.get_model('news', 'InstitutionalReport').objects.filter(status='awaiting_approval', awaiting_since__isnull=True) \
        .update(awaiting_since=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0145_coordinated_clusters'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionalreport',
            name='awaiting_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(start_clock, migrations.RunPython.noop),
    ]
