# Generated by Django 5.1.15 on 2026-10-05 23:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0146_report_awaiting_since'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('candidates', models.PositiveSmallIntegerField(default=0)),
                ('diagnosis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position_scan', to='news.spindiagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='PositionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('post', 'Wpis na X'), ('statement', 'Wystąpienie w Sejmie'), ('vote', 'Głosowanie w Sejmie')], max_length=12)),
                ('source_key', models.CharField(help_text='post:<id>, record:<id> albo ballot:<id>.', max_length=40)),
                ('source_url', models.URLField(max_length=1024)),
                ('source_date', models.DateField()),
                ('source_title', models.CharField(blank=True, max_length=300)),
                ('earlier_text', models.TextField(help_text='Wcześniejsza wypowiedź (fragment) albo opis głosu.')),
                ('similarity', models.FloatField(default=0)),
                ('relation', models.CharField(choices=[('pending', 'Czeka na sprawdzenie'), ('change', 'Zmiana stanowiska'), ('same', 'To samo stanowisko'), ('off_topic', 'Nie na temat'), ('unclear', 'Nie da się ocenić (cytat bez potwierdzenia)')], db_index=True, default='pending', max_length=12)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('explanation', models.CharField(blank=True, max_length=400)),
                ('quote_then', models.CharField(blank=True, max_length=400)),
                ('quote_now', models.CharField(blank=True, max_length=400)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('checked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_checks', to='news.spindiagnosis')),
                ('earlier_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='news.politicalpost')),
            ],
            options={
                'ordering': ['-source_date', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('diagnosis', 'source_key'), name='position_check_once')],
            },
        ),
    ]
