# Generated by Django 5.1.15 on 2026-10-06 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0148_reception_checks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('raporty', 'Raporty dla instytucji'), ('pilot', 'Pilot przeszłość.today')], db_index=True, max_length=8, verbose_name='rodzaj')),
                ('name', models.CharField(max_length=120, verbose_name='imię i nazwisko')),
                ('organisation', models.CharField(blank=True, max_length=160, verbose_name='organizacja')),
                ('org_type', models.CharField(choices=[('agencja', 'Agencja PR lub public affairs'), ('firma', 'Dział komunikacji firmy'), ('instytucja', 'Instytucja publiczna lub ambasada'), ('nauka', 'Uczelnia lub think tank'), ('redakcja', 'Redakcja lub dziennikarz'), ('ngo', 'Organizacja pozarządowa'), ('partia', 'Partia lub sztab'), ('inne', 'Inne')], default='inne', max_length=12, verbose_name='typ odbiorcy')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('message', models.TextField(blank=True, max_length=2000, verbose_name='wiadomość')),
                ('newsletter', models.BooleanField(default=False, verbose_name='zgoda na newsletter')),
                ('status', models.CharField(choices=[('pending', 'czeka na potwierdzenie e-mail'), ('confirmed', 'potwierdzony - do kontaktu'), ('contacted', 'w rozmowie'), ('won', 'umowa'), ('lost', 'bez umowy')], db_index=True, default='pending', max_length=12)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('consent_version', models.CharField(max_length=24)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('owner_notified_at', models.DateTimeField(blank=True, null=True)),
                ('pilot_until', models.DateField(blank=True, null=True, verbose_name='pilot Pro do')),
                ('notes', models.TextField(blank=True, verbose_name='notatki zespołu')),
            ],
            options={
                'verbose_name': 'zapytanie (raporty, pilot)',
                'verbose_name_plural': 'zapytania: raporty dla instytucji i piloci',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True, verbose_name='poniedziałek')),
                ('week_end', models.DateField(verbose_name='niedziela')),
                ('status', models.CharField(choices=[('ready', 'gotowy (prywatny)'), ('empty', 'za mało danych'), ('failed', 'błąd')], default='ready', max_length=8)),
                ('data', models.JSONField(default=dict, verbose_name='dane zbiorcze')),
                ('pdf', models.BinaryField(null=True)),
                ('csv', models.BinaryField(null=True)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('public_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='próbka publiczna od')),
                ('public_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'raport tygodniowy dla instytucji',
                'verbose_name_plural': 'raporty tygodniowe dla instytucji',
                'ordering': ['-week_start'],
            },
        ),
    ]
