# Generated by Django 5.1.15 on 2026-10-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0149_sales_leads_weekly_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZamowienieSygnal',
            fields=[
            ],
            options={
                'verbose_name': 'zamówienie publiczne (sygnał)',
                'verbose_name_plural': 'Zamówienia publiczne: strony i WCAG',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.agentnote',),
        ),
        migrations.AlterField(
            model_name='agentnote',
            name='agent',
            field=models.CharField(choices=[('strateg', 'strateg'), ('pielgrzym', 'pielgrzym'), ('ekspert', 'ekspert'), ('recenzent', 'recenzent'), ('projektant', 'projektant'), ('kartograf', 'kartograf'), ('zwiadowca', 'zwiadowca'), ('prawnik', 'prawnik'), ('dziennikarz', 'dziennikarz'), ('kontroler', 'kontroler'), ('architekt', 'architekt'), ('wynalazca', 'wynalazca'), ('technolog', 'technolog'), ('automatyk', 'automatyk'), ('opiekun', 'opiekun'), ('dyrygent', 'dyrygent'), ('zamowienia', 'zamowienia')], max_length=12),
        ),
    ]
