# Generated by Django 5.1.15 on 2026-10-06 12:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0150_zamowienia_publiczne'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024)),
                ('url_sha256', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('cited_by', models.JSONField(blank=True, default=list, help_text='Odwołania: diagnosis:<id>, sejm:<id>, topic:<temat>.')),
                ('first_cited_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('archive_url', models.URLField(blank=True, max_length=1500)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archive_status', models.CharField(blank=True, db_index=True, max_length=16)),
                ('archive_attempts', models.PositiveSmallIntegerField(default=0)),
                ('first_sha256', models.CharField(blank=True, max_length=64)),
                ('last_sha256', models.CharField(blank=True, max_length=64)),
                ('last_checked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('check_status', models.CharField(blank=True, max_length=24)),
                ('changed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('change_count', models.PositiveSmallIntegerField(default=0)),
                ('changed_archive_url', models.URLField(blank=True, max_length=1500)),
                ('history', models.JSONField(blank=True, default=list, help_text='Ostatnie sprawdzenia: data, skrót, kod HTTP (bez treści).')),
            ],
            options={
                'verbose_name': 'artykuł cytowany (strażnik mediów)',
                'verbose_name_plural': 'artykuły cytowane (strażnik mediów)',
                'ordering': ['-first_cited_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SejmVideoSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('place', models.CharField(choices=[('sala', 'Sala posiedzeń'), ('komisja', 'Komisja')], max_length=12)),
                ('video_unid', models.CharField(blank=True, max_length=32)),
                ('video_url', models.URLField(blank=True, max_length=1024)),
                ('offset_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('offset_exact', models.BooleanField(default=False, help_text='Sekunda z czasu wystąpienia w API Sejmu (sala); w komisji szacunek z położenia w zapisie przebiegu.')),
                ('rank_score', models.PositiveIntegerField(default=0, help_text='Liczba słów wystąpienia (to samo kryterium dla wszystkich).')),
                ('status', models.CharField(choices=[('flagged', 'Strażnik: warte sprawdzenia — czeka na decyzję o badaniu'), ('queued', 'W kolejce do płatnej diagnozy'), ('pending_review', 'Czeka na zatwierdzenie'), ('approved', 'Zatwierdzona'), ('rejected', 'Odrzucona'), ('failed', 'Błąd analizy'), ('not_applicable', 'Bez treści do oceny'), ('withdrawn', 'Wycofana')], db_index=True, default='queued', max_length=16)),
                ('verdict', models.CharField(blank=True, choices=[('spin', 'Spin'), ('partial', 'Częściowy spin'), ('no_spin', 'Bez spinu'), ('unclear', 'Nie da się ocenić')], max_length=12)),
                ('intensity', models.PositiveSmallIntegerField(default=0)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('plain', models.JSONField(blank=True, default=dict)),
                ('analysis', models.TextField(blank=True)),
                ('techniques', models.JSONField(blank=True, default=list)),
                ('claims', models.JSONField(blank=True, default=list)),
                ('lab', models.JSONField(blank=True, default=dict)),
                ('limitations', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('diagnosed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_reason', models.CharField(blank=True, max_length=240)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_reason', models.CharField(blank=True, max_length=400)),
                ('figure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sejm_video_spins', to='news.publicfigure')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_spin', to='news.publicrecord')),
            ],
            options={
                'verbose_name': 'diagnoza wystąpienia w Sejmie',
                'verbose_name_plural': 'diagnozy wystąpień w Sejmie',
                'ordering': ['-day', '-rank_score', '-pk'],
            },
        ),
    ]
