# Generated by Django 5.1.15 on 2026-10-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0153_zwiadowca_rozwiazan'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildticket',
            name='issue_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildticket',
            name='issue_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildticket',
            name='issue_url',
            field=models.URLField(blank=True),
        ),
    ]
