# Poczta (właściciel 6.10): skrzynki projektów czytane i obsługiwane przez agenta; metadane i treść wiadomości (treść 180 dni), stan skrzynki.
# Generated by Django 5.1.15 on 2026-10-06 22:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0156_organisation_identifiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox', models.CharField(max_length=40, unique=True)),
                ('uidvalidity', models.CharField(blank=True, max_length=32)),
                ('last_uid', models.PositiveBigIntegerField(default=0)),
                ('last_ok_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_errors', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Stan skrzynki Poczty',
                'verbose_name_plural': 'Stany skrzynek Poczty',
            },
        ),
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox', models.CharField(db_index=True, max_length=40)),
                ('uid', models.PositiveBigIntegerField()),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=512)),
                ('in_reply_to', models.CharField(blank=True, max_length=512)),
                ('references', models.TextField(blank=True)),
                ('thread_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('sender', models.CharField(blank=True, max_length=320)),
                ('sender_address', models.CharField(blank=True, db_index=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('auto_generated', models.BooleanField(default=False, help_text='Auto-Submitted, Precedence bulk/list, mailer-daemon: nigdy nie odpowiadamy.')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('category', models.CharField(blank=True, choices=[('correction', 'Sprostowanie lub skarga na diagnozę'), ('question', 'Pytanie czytelnika'), ('press', 'Prasa, dziennikarz'), ('partner', 'Partner, zapytanie handlowe (przychodzące)'), ('institution', 'Instytucja, pismo urzędowe'), ('spam', 'Spam'), ('other', 'Inne')], db_index=True, max_length=16)),
                ('category_reason', models.CharField(blank=True, max_length=300)),
                ('confidence', models.PositiveSmallIntegerField(default=0, help_text='0-100 z modelu; poniżej progu zawsze do właściciela.')),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('classify_attempts', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'Nowa'), ('replied', 'Odpowiedziano automatycznie'), ('escalated', 'Do właściciela'), ('skipped', 'Pominięta'), ('failed', 'Błąd wysyłki')], db_index=True, default='new', max_length=12)),
                ('status_reason', models.CharField(blank=True, max_length=300)),
                ('reply_draft', models.TextField(blank=True)),
                ('reply_checks', models.JSONField(blank=True, default=list, help_text='Zarzuty kontroli Recenzenta do szkicu (puste = czysto).')),
                ('reply_sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reply_message_id', models.CharField(blank=True, max_length=512)),
                ('escalated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('digest_sent_at', models.DateTimeField(blank=True, null=True)),
                ('body_deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Wiadomość Poczty',
                'verbose_name_plural': 'Wiadomości Poczty',
                'ordering': ['-fetched_at', '-pk'],
                'unique_together': {('mailbox', 'uid')},
            },
        ),
    ]
