# Generated by Django 5.1.15 on 2026-10-07 21:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0157_poczta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailOutboxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Nazwa pliku listu bez rozszerzenia.', max_length=120)),
                ('mailbox', models.CharField(db_index=True, max_length=40)),
                ('recipient', models.CharField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, choices=[('dostep-do-danych', 'Dostęp do danych (API, biblioteki treści)'), ('instytucja', 'Wniosek lub pismo do instytucji'), ('partner', 'Partner (współpraca, zgoda, porozumienie)'), ('odpowiedz', 'Odpowiedź w istniejącym wątku')], max_length=24)),
                ('status', models.CharField(choices=[('sent', 'Wysłano'), ('failed', 'Błąd wysyłki'), ('blocked', 'Zatrzymane przez kontrolę'), ('duplicate', 'Pominięte: już wysłane')], db_index=True, max_length=12)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('message_id', models.CharField(blank=True, max_length=512)),
                ('copy_saved', models.BooleanField(default=False, help_text='Kopia zapisana w folderze Wysłane skrzynki (IMAP APPEND).')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('digest_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Wpis Poczty wychodzącej',
                'verbose_name_plural': 'Wpisy Poczty wychodzącej',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
