# Generated by Django 5.1.15 on 2026-10-09 03:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0158_poczta_wychodzaca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicCommentAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Oczekuje na przegląd'), ('accepted', 'Uwzględnione'), ('rejected', 'Odrzucone')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'odwołanie od ukrycia komentarza',
                'verbose_name_plural': 'odwołania od ukrycia komentarzy',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DailyMessageOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarity', models.CharField(choices=[('positive', 'Trafna diagnoza'), ('negative', 'Nietrafna diagnoza')], max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='cliniccomment',
            name='clinic_comment_exactly_one_target',
        ),
        migrations.AddField(
            model_name='cliniccomment',
            name='daily_message',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.clinicdailymessage'),
        ),
        migrations.AddIndex(
            model_name='cliniccomment',
            index=models.Index(fields=['daily_message', 'created_at'], name='clinic_comment_daily_date'),
        ),
        migrations.AddConstraint(
            model_name='cliniccomment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('daily_message__isnull', True), ('diagnosis__isnull', False), ('interview__isnull', True)), models.Q(('daily_message__isnull', True), ('diagnosis__isnull', True), ('interview__isnull', False)), models.Q(('daily_message__isnull', False), ('diagnosis__isnull', True), ('interview__isnull', True)), _connector='OR'), name='clinic_comment_exactly_one_target'),
        ),
        migrations.AddField(
            model_name='cliniccommentappeal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_comment_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliniccommentappeal',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='news.cliniccomment'),
        ),
        migrations.AddField(
            model_name='cliniccommentappeal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailymessageopinion',
            name='daily_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='news.clinicdailymessage'),
        ),
        migrations.AddField(
            model_name='dailymessageopinion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_message_opinions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dailymessageopinion',
            constraint=models.UniqueConstraint(fields=('user', 'daily_message'), name='one_opinion_user_daily_message'),
        ),
        migrations.AddConstraint(
            model_name='dailymessageopinion',
            constraint=models.CheckConstraint(condition=models.Q(('polarity__in', ['positive', 'negative'])), name='daily_opinion_valid_polarity'),
        ),
    ]
