# Generated by Django 5.1.15 on 2026-10-09 03:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0159_clinic_daily_message_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpost',
            name='push_latency_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationpost',
            name='push_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='quiet_hours_end',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='quiet_hours_start',
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='wake_person_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='PushDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_deliveries', to='news.notification')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.pushsubscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('notification', 'subscription'), name='unique_alert_push_device_113')],
            },
        ),
    ]
